import { ns } from "../types";

export const birth = ns({
  en: {
    // Sub-header
    headerTitle: "Birth Declaration",
    headerSubtitle: "Online Application",

    // Step titles & subtitles
    step1Title: "Header",
    step1Subtitle: "Jurisdiction and document details",
    step2Title: "The Child",
    step2Subtitle: "Details of the newborn",
    step3Title: "Mother",
    step3Subtitle: "Mother's particulars",
    step4Title: "Father",
    step4Subtitle: "Father's particulars",
    step5Title: "Informant",
    step5Subtitle: "Reporter of the birth",
    step6Title: "Review",
    step6Subtitle: "Check and submit your declaration",

    stepOf: "Step {n} of {m}",

    // Step indicator labels (short)
    stepHeader: "Header",
    stepChild: "The Child",
    stepMother: "Mother",
    stepFather: "Father",
    stepInformant: "Informant",
    stepReview: "Review",

    // Common select / shared
    selectPlaceholder: "Select...",

    // Document / fee
    documentNo: "Document No.",
    autoGenerated: "Auto-generated",
    fee: "Fee",

    // Step 1 — Header
    legalBasisTitle: "Legal basis",
    legalBasisText:
      "Pursuant to the Family Law No. 44/NA, dated 14/06/2018. The date of declaration is set automatically on submission.",

    // Step 2 — The Child
    childUinNote:
      "A Unique Identification Number (UIN) is assigned to the child on registration.",
    fullNameLabel: "Full Name (Lao / English)",
    childNamePlaceholder: "Child's full name",
    genderLabel: "Gender",
    dobLabel: "Date of Birth",
    typeOfBirthLabel: "Type of Birth",
    birthOrderLabel: "Birth Order (child no.)",
    birthOrderPlaceholder: "e.g. 1",
    twinNameLabel: "Twin — Full Name",
    twinNamePlaceholder: "Co-delivered child",
    twinGenderLabel: "Twin — Gender",
    ethnicityLabel: "Ethnicity",
    nationalityLabel: "Nationality",
    religionLabel: "Religion",
    placeOfBirthSection: "Place of birth",
    pobVillageLabel: "Village of birth",
    countryLabel: "Country",
    countryPlaceholder: "Country",
    currentAddressSection: "Current address",
    additionalDetailsSection: "Additional details (optional)",
    weightLabel: "Weight (kg)",
    weightPlaceholder: "e.g. 3.2",
    heightLabel: "Height (cm)",
    heightPlaceholder: "e.g. 50",
    bloodTypeLabel: "Blood Type / Group",
    deliveryModeLabel: "Mode of Delivery",
    assistedByLabel: "Assisted by",
    assistedByPlaceholder: "Midwife / doctor",
    fingerprintLabel: "Fingerprint Code",
    fingerprintPlaceholder: "Biometric code",

    // House number (address)
    houseNoLabel: "House No.",
    houseNoPlaceholder: "House number",

    // Step 3 — Mother
    motherNote: "Section 2 — the child's mother.",
    // Step 4 — Father
    fatherNote: "Section 3 — the child's father.",
    fatherUnknownTitle: "Father unknown / not declared",
    fatherUnknownSubtitle: "Submit a sole-parent declaration",

    // Parent section
    parentNamePlaceholder: "Full name",
    maritalStatusLabel: "Marital Status",
    censusOrIdLabel: "Census Book No. / ID Card No.",
    censusOrIdPlaceholder: "One identifier + issue date",
    ethnicGroupLabel: "Ethnic Group",
    educationLabel: "Education Level",
    occupationLabel: "Occupation",
    occupationPlaceholder: "Occupation",
    parentFingerprintPlaceholder: "Biometric fingerprint code",

    // Step 5 — Informant
    informantNote: "Section 4 — the person reporting the birth.",
    informantNamePlaceholder: "Informant's full name",
    relationshipLabel: "Relationship to Child",
    relationshipPlaceholder: "e.g. Mother, Father",
    phoneLabel: "Phone Number",
    phonePlaceholder: "+856...",
    emailLabel: "Email (optional)",
    emailPlaceholder: "name@email.com",

    // Step 6 — Review
    reviewWarning:
      "Please review the declaration before submitting. The Village Chief, birth attendant (if any) and informant sign the form at the village office.",
    reviewProvinceDistrictVillage: "Province / District / Village",
    reviewName: "Name",
    reviewGenderDob: "Gender / DoB",
    reviewBirth: "Birth",
    reviewPlaceOfBirth: "Place of birth",
    reviewIdCensus: "ID / Census",
    reviewStatus: "Status",
    reviewFatherUnknown: "Unknown / sole-parent declaration",
    reviewRelationship: "Relationship",
    reviewPhone: "Phone",

    // Options — gender
    optFemale: "Female",
    optMale: "Male",
    // Options — marital
    optSingle: "Single",
    optMarried: "Married",
    optWidowed: "Widowed",
    optDivorced: "Divorced",
    // Options — nationality
    optNatLao: "Lao",
    optNatThai: "Thai",
    optNatVietnamese: "Vietnamese",
    optNatChinese: "Chinese",
    optNatCambodian: "Cambodian",
    optNatOther: "Other",
    // Options — ethnicity
    optEthLao: "Lao",
    optEthKhmu: "Khmu",
    optEthHmong: "Hmong",
    optEthPhouthai: "Phouthai",
    optEthTai: "Tai",
    optEthOther: "Other",
    // Options — ethnic group
    optGrpLaoTai: "Lao-Tai",
    optGrpMonKhmer: "Mon-Khmer",
    optGrpHmongIuMien: "Hmong-Iu Mien",
    optGrpSinoTibetan: "Sino-Tibetan",
    optGrpOther: "Other",
    // Options — religion
    optRelBuddhism: "Buddhism",
    optRelChristianity: "Christianity",
    optRelIslam: "Islam",
    optRelBahai: "Bahá'í",
    optRelAnimism: "Animism",
    optRelNone: "None",
    optRelOther: "Other",
    // Options — education
    optEduNone: "None",
    optEduPrimary: "Primary",
    optEduLowerSecondary: "Lower Secondary",
    optEduUpperSecondary: "Upper Secondary",
    optEduVocational: "Vocational",
    optEduBachelor: "Bachelor",
    optEduMaster: "Master",
    optEduDoctorate: "Doctorate",
    // Options — delivery mode
    optDelNatural: "Natural",
    optDelCsection: "C-section",
    // Options — birth type
    optBirthSingle: "Single",
    optBirthTwins: "Twins",
    // Options — blood type
    optBloodA: "A",
    optBloodB: "B",
    optBloodAB: "AB",
    optBloodO: "O",
    optBloodUnknown: "Unknown",

    // Bottom CTA
    submitting: "Submitting…",
    submitDeclaration: "Submit Declaration",
    continue: "Continue",

    // Success
    successTitle: "Birth Declaration Submitted!",
    successText:
      "The declaration has been received. The village office will review it and a UIN will be assigned to the child.",
    successChild: "Child",
    successInformant: "Informant",
    successEstReview: "Est. review",
    successEstReviewValue: "≤ 5 working days",
    successStatus: "Status",
    successStatusValue: "Submitted",
    backToHome: "Back to Home",
    trackHint: "Track your declaration in the History tab",
    emptyValue: "—",
  },
  lo: {
    // Sub-header
    headerTitle: "ໃບແຈ້ງເກີດ",
    headerSubtitle: "ຍື່ນຄຳຮ້ອງອອນລາຍ",

    // Step titles & subtitles
    step1Title: "ຫົວເລື່ອງ",
    step1Subtitle: "ເຂດອຳນາດ ແລະ ລາຍລະອຽດເອກະສານ",
    step2Title: "ເດັກນ້ອຍ",
    step2Subtitle: "ລາຍລະອຽດຂອງເດັກເກີດໃໝ່",
    step3Title: "ແມ່",
    step3Subtitle: "ຂໍ້ມູນຂອງແມ່",
    step4Title: "ພໍ່",
    step4Subtitle: "ຂໍ້ມູນຂອງພໍ່",
    step5Title: "ຜູ້ແຈ້ງ",
    step5Subtitle: "ຜູ້ແຈ້ງການເກີດ",
    step6Title: "ກວດຄືນ",
    step6Subtitle: "ກວດ ແລະ ຍື່ນຄຳແຈ້ງຂອງທ່ານ",

    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // Step indicator labels (short)
    stepHeader: "ຫົວເລື່ອງ",
    stepChild: "ເດັກນ້ອຍ",
    stepMother: "ແມ່",
    stepFather: "ພໍ່",
    stepInformant: "ຜູ້ແຈ້ງ",
    stepReview: "ກວດຄືນ",

    // Common select / shared
    selectPlaceholder: "ເລືອກ...",

    // Document / fee
    documentNo: "ເລກທີເອກະສານ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",
    fee: "ຄ່າທຳນຽມ",

    // Step 1 — Header
    legalBasisTitle: "ພື້ນຖານທາງກົດໝາຍ",
    legalBasisText:
      "ອີງຕາມກົດໝາຍວ່າດ້ວຍຄອບຄົວ ສະບັບເລກທີ 44/ສພຊ, ລົງວັນທີ 14/06/2018. ວັນທີແຈ້ງຈະຖືກກຳນົດອັດຕະໂນມັດເມື່ອຍື່ນ.",

    // Step 2 — The Child
    childUinNote: "ເລກປະຈຳຕົວເອກະລັກ (UIN) ຈະຖືກກຳນົດໃຫ້ເດັກເມື່ອລົງທະບຽນ.",
    fullNameLabel: "ຊື່ ແລະ ນາມສະກຸນ (ລາວ / ອັງກິດ)",
    childNamePlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງເດັກ",
    genderLabel: "ເພດ",
    dobLabel: "ວັນເດືອນປີເກີດ",
    typeOfBirthLabel: "ປະເພດການເກີດ",
    birthOrderLabel: "ລຳດັບການເກີດ (ບຸດຄົນທີ)",
    birthOrderPlaceholder: "ຕົວຢ່າງ 1",
    twinNameLabel: "ຝາແຝດ — ຊື່ ແລະ ນາມສະກຸນ",
    twinNamePlaceholder: "ເດັກທີ່ເກີດຮ່ວມ",
    twinGenderLabel: "ຝາແຝດ — ເພດ",
    ethnicityLabel: "ຊົນເຜົ່າ",
    nationalityLabel: "ສັນຊາດ",
    religionLabel: "ສາສະໜາ",
    placeOfBirthSection: "ສະຖານທີ່ເກີດ",
    pobVillageLabel: "ບ້ານທີ່ເກີດ",
    countryLabel: "ປະເທດ",
    countryPlaceholder: "ປະເທດ",
    currentAddressSection: "ທີ່ຢູ່ປັດຈຸບັນ",
    additionalDetailsSection: "ລາຍລະອຽດເພີ່ມເຕີມ (ບໍ່ບັງຄັບ)",
    weightLabel: "ນ້ຳໜັກ (ກິໂລ)",
    weightPlaceholder: "ຕົວຢ່າງ 3.2",
    heightLabel: "ສ່ວນສູງ (ຊມ)",
    heightPlaceholder: "ຕົວຢ່າງ 50",
    bloodTypeLabel: "ກຸ່ມເລືອດ",
    deliveryModeLabel: "ວິທີການເກີດ",
    assistedByLabel: "ຜູ້ຊ່ວຍເກີດ",
    assistedByPlaceholder: "ຜະດຸງຄັນ / ແພດ",
    fingerprintLabel: "ລະຫັດລາຍນິ້ວມື",
    fingerprintPlaceholder: "ລະຫັດຊີວະມິຕິ",

    // House number (address)
    houseNoLabel: "ເລກທີເຮືອນ",
    houseNoPlaceholder: "ເລກທີເຮືອນ",

    // Step 3 — Mother
    motherNote: "ພາກທີ 2 — ແມ່ຂອງເດັກ.",
    // Step 4 — Father
    fatherNote: "ພາກທີ 3 — ພໍ່ຂອງເດັກ.",
    fatherUnknownTitle: "ບໍ່ຮູ້ພໍ່ / ບໍ່ໄດ້ແຈ້ງ",
    fatherUnknownSubtitle: "ຍື່ນຄຳແຈ້ງຜູ້ປົກຄອງຝ່າຍດຽວ",

    // Parent section
    parentNamePlaceholder: "ຊື່ ແລະ ນາມສະກຸນ",
    maritalStatusLabel: "ສະຖານະການແຕ່ງງານ",
    censusOrIdLabel: "ເລກປຶ້ມສຳມະໂນຄົວ / ເລກບັດປະຈຳຕົວ",
    censusOrIdPlaceholder: "ໃສ່ໜຶ່ງເລກ + ວັນທີອອກ",
    ethnicGroupLabel: "ກຸ່ມຊົນເຜົ່າ",
    educationLabel: "ລະດັບການສຶກສາ",
    occupationLabel: "ອາຊີບ",
    occupationPlaceholder: "ອາຊີບ",
    parentFingerprintPlaceholder: "ລະຫັດລາຍນິ້ວມືຊີວະມິຕິ",

    // Step 5 — Informant
    informantNote: "ພາກທີ 4 — ຜູ້ແຈ້ງການເກີດ.",
    informantNamePlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງຜູ້ແຈ້ງ",
    relationshipLabel: "ຄວາມສຳພັນກັບເດັກ",
    relationshipPlaceholder: "ຕົວຢ່າງ ແມ່, ພໍ່",
    phoneLabel: "ເບີໂທລະສັບ",
    phonePlaceholder: "+856...",
    emailLabel: "ອີເມວ (ບໍ່ບັງຄັບ)",
    emailPlaceholder: "name@email.com",

    // Step 6 — Review
    reviewWarning:
      "ກະລຸນາກວດຄືນຄຳແຈ້ງກ່ອນຍື່ນ. ນາຍບ້ານ, ຜູ້ຊ່ວຍເກີດ (ຖ້າມີ) ແລະ ຜູ້ແຈ້ງ ຈະເຊັນໃບແຈ້ງຢູ່ຫ້ອງການບ້ານ.",
    reviewProvinceDistrictVillage: "ແຂວງ / ເມືອງ / ບ້ານ",
    reviewName: "ຊື່",
    reviewGenderDob: "ເພດ / ວັນເກີດ",
    reviewBirth: "ການເກີດ",
    reviewPlaceOfBirth: "ສະຖານທີ່ເກີດ",
    reviewIdCensus: "ບັດປະຈຳຕົວ / ສຳມະໂນຄົວ",
    reviewStatus: "ສະຖານະ",
    reviewFatherUnknown: "ບໍ່ຮູ້ / ຄຳແຈ້ງຜູ້ປົກຄອງຝ່າຍດຽວ",
    reviewRelationship: "ຄວາມສຳພັນ",
    reviewPhone: "ໂທລະສັບ",

    // Options — gender
    optFemale: "ຍິງ",
    optMale: "ຊາຍ",
    // Options — marital
    optSingle: "ໂສດ",
    optMarried: "ແຕ່ງງານແລ້ວ",
    optWidowed: "ໝ້າຍ",
    optDivorced: "ຢ່າຮ້າງ",
    // Options — nationality
    optNatLao: "ລາວ",
    optNatThai: "ໄທ",
    optNatVietnamese: "ຫວຽດນາມ",
    optNatChinese: "ຈີນ",
    optNatCambodian: "ກຳປູເຈຍ",
    optNatOther: "ອື່ນໆ",
    // Options — ethnicity
    optEthLao: "ລາວ",
    optEthKhmu: "ຂະມຸ",
    optEthHmong: "ມົ້ງ",
    optEthPhouthai: "ຜູ້ໄທ",
    optEthTai: "ໄຕ",
    optEthOther: "ອື່ນໆ",
    // Options — ethnic group
    optGrpLaoTai: "ລາວ-ໄຕ",
    optGrpMonKhmer: "ມອນ-ຂະແມ",
    optGrpHmongIuMien: "ມົ້ງ-ອິວມ້ຽນ",
    optGrpSinoTibetan: "ຈີນ-ທິເບດ",
    optGrpOther: "ອື່ນໆ",
    // Options — religion
    optRelBuddhism: "ພຸດ",
    optRelChristianity: "ຄຣິສ",
    optRelIslam: "ອິສລາມ",
    optRelBahai: "ບາໄຮ",
    optRelAnimism: "ນັບຖືຜີ",
    optRelNone: "ບໍ່ມີ",
    optRelOther: "ອື່ນໆ",
    // Options — education
    optEduNone: "ບໍ່ມີ",
    optEduPrimary: "ປະຖົມ",
    optEduLowerSecondary: "ມັດທະຍົມຕົ້ນ",
    optEduUpperSecondary: "ມັດທະຍົມປາຍ",
    optEduVocational: "ວິຊາຊີບ",
    optEduBachelor: "ປະລິນຍາຕີ",
    optEduMaster: "ປະລິນຍາໂທ",
    optEduDoctorate: "ປະລິນຍາເອກ",
    // Options — delivery mode
    optDelNatural: "ເກີດທຳມະຊາດ",
    optDelCsection: "ຜ່າຕັດ",
    // Options — birth type
    optBirthSingle: "ດ່ຽວ",
    optBirthTwins: "ຝາແຝດ",
    // Options — blood type
    optBloodA: "A",
    optBloodB: "B",
    optBloodAB: "AB",
    optBloodO: "O",
    optBloodUnknown: "ບໍ່ຮູ້",

    // Bottom CTA
    submitting: "ກຳລັງຍື່ນ…",
    submitDeclaration: "ຍື່ນຄຳແຈ້ງ",
    continue: "ຕໍ່ໄປ",

    // Success
    successTitle: "ຍື່ນໃບແຈ້ງເກີດສຳເລັດແລ້ວ!",
    successText:
      "ໄດ້ຮັບຄຳແຈ້ງແລ້ວ. ຫ້ອງການບ້ານຈະກວດສອບ ແລະ ຈະກຳນົດເລກ UIN ໃຫ້ເດັກ.",
    successChild: "ເດັກ",
    successInformant: "ຜູ້ແຈ້ງ",
    successEstReview: "ປະມານການກວດສອບ",
    successEstReviewValue: "ບໍ່ເກີນ 5 ວັນລັດຖະການ",
    successStatus: "ສະຖານະ",
    successStatusValue: "ຍື່ນແລ້ວ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຄຳແຈ້ງຂອງທ່ານໃນແຖບປະຫວັດ",
    emptyValue: "—",
  },
});
