import { ns } from "../types";

export const death = ns({
  en: {
    // Sub-header
    title: "Death Declaration",
    subtitle: "Online Application",

    // Steps
    step1Title: "Header",
    step1Subtitle: "Jurisdiction and document details",
    step2Title: "The Deceased",
    step2Subtitle: "Details of the deceased person",
    step3Title: "Mother",
    step3Subtitle: "Mother of the deceased",
    step4Title: "Father",
    step4Subtitle: "Father of the deceased",
    step5Title: "Informant",
    step5Subtitle: "Reporter of the death",
    step6Title: "Review",
    step6Subtitle: "Check and submit your declaration",
    stepOf: "Step {n} of {m}",

    // Section intros
    deceasedIntro: "Section 1 — details of the deceased person.",
    motherIntro: "Section 2 — the mother of the deceased.",
    fatherIntro: "Section 3 — the father of the deceased.",
    informantIntro: "Section 4 — the person reporting the death.",

    // Step 1 — Header
    documentNo: "Document No.",
    autoGenerated: "Auto-generated",
    legalBasis: "Legal basis",
    legalBasisText:
      "Pursuant to the Family Law No. 44/NA, dated 14/06/2018. The date of declaration is set automatically on submission.",

    // Parent toggle
    parentDeceasedUnknown: "Parent deceased / unknown",
    skipThisSection: "Skip this section",
    statusDeceasedUnknown: "Deceased / unknown",

    // Section labels
    secDemographics: "Demographics (optional)",
    secCurrentAddressOptional: "Current address (if applicable)",
    secCurrentAddress: "Current address",
    secEducationWork: "Education & work (optional)",
    secPlaceOfDeath: "Place of death",
    secTheDeath: "The death",
    secAdditionalDetails: "Additional details (optional)",

    // Field labels
    fullName: "Full Name (Lao / English)",
    dobOptional: "Date of Birth (optional)",
    dob: "Date of Birth",
    maritalStatusOptional: "Marital Status (optional)",
    maritalStatus: "Marital Status",
    ethnicity: "Ethnicity",
    nationality: "Nationality",
    ethnicGroup: "Ethnic Group",
    religion: "Religion",
    censusOrIdOptional: "Census Book No. / ID Card No. (if applicable)",
    censusOrId: "Census Book No. / ID Card No.",
    educationLevel: "Education Level",
    occupation: "Occupation",
    workplace: "Workplace",
    fingerprintCode: "Fingerprint Code",
    houseNo: "House No.",
    gender: "Gender",
    dateOfDeath: "Date of Death",
    timeOfDeathOptional: "Time of Death (optional)",
    causeOfDeath: "Cause of Death",
    causeSpecify: "Cause — please specify",
    relationshipToDeceased: "Relationship to Deceased",
    phoneNumber: "Phone Number",
    emailOptional: "Email (optional)",
    villageLabel: "Village",

    // Placeholders
    phHouseNo: "House number",
    phSelect: "Select...",
    phDeceasedName: "Deceased's full name",
    phFullName: "Full name",
    phInformantName: "Informant's full name",
    phOneIdentifier: "One identifier + issue date",
    phOccupation: "Occupation",
    phWorkplace: "Workplace",
    phBiometric: "Biometric code",
    phTime: "HH:MM",
    phSpecifyCause: "Specify the cause",
    phRelationship: "e.g. Son, Spouse",
    phPhone: "+856...",
    phEmail: "name@email.com",

    // Review
    reviewWarning:
      "Please review the declaration before submitting. The Village Chief and informant sign the form at the village office.",
    rowProvinceDistrictVillage: "Province / District / Village",
    rowName: "Name",
    rowGenderDob: "Gender / DoB",
    rowPlaceOfDeath: "Place of death",
    rowDateCause: "Date / cause",
    rowStatus: "Status",
    rowRelationship: "Relationship",
    rowPhone: "Phone",

    // Buttons
    continue: "Continue",
    submitDeclaration: "Submit Declaration",
    submitting: "Submitting…",

    // Success
    successTitle: "Death Declaration Submitted!",
    successText:
      "The declaration has been received. On approval, the deceased will be removed from the household record.",
    sumDeceased: "Deceased",
    sumDocumentNo: "Document No.",
    sumInformant: "Informant",
    sumFee: "Fee",
    sumEstReview: "Est. review",
    sumEstReviewValue: "≤ 5 working days",
    sumStatus: "Status",
    sumStatusValue: "Submitted",
    backToHome: "Back to Home",
    trackHint: "Track your declaration in the History tab",
    dash: "—",
  },
  lo: {
    // Sub-header
    title: "ໃບແຈ້ງເສຍຊີວິດ",
    subtitle: "ຍື່ນຄຳຮ້ອງອອນລາຍ",

    // Steps
    step1Title: "ຫົວເລື່ອງ",
    step1Subtitle: "ເຂດອຳນາດ ແລະ ລາຍລະອຽດເອກະສານ",
    step2Title: "ຜູ້ເສຍຊີວິດ",
    step2Subtitle: "ລາຍລະອຽດຂອງຜູ້ເສຍຊີວິດ",
    step3Title: "ແມ່",
    step3Subtitle: "ແມ່ຂອງຜູ້ເສຍຊີວິດ",
    step4Title: "ພໍ່",
    step4Subtitle: "ພໍ່ຂອງຜູ້ເສຍຊີວິດ",
    step5Title: "ຜູ້ແຈ້ງ",
    step5Subtitle: "ຜູ້ແຈ້ງການເສຍຊີວິດ",
    step6Title: "ກວດສອບ",
    step6Subtitle: "ກວດສອບ ແລະ ສົ່ງຄຳຮ້ອງຂອງທ່ານ",
    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // Section intros
    deceasedIntro: "ພາກທີ 1 — ລາຍລະອຽດຂອງຜູ້ເສຍຊີວິດ.",
    motherIntro: "ພາກທີ 2 — ແມ່ຂອງຜູ້ເສຍຊີວິດ.",
    fatherIntro: "ພາກທີ 3 — ພໍ່ຂອງຜູ້ເສຍຊີວິດ.",
    informantIntro: "ພາກທີ 4 — ຜູ້ແຈ້ງການເສຍຊີວິດ.",

    // Step 1 — Header
    documentNo: "ເລກທີເອກະສານ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",
    legalBasis: "ພື້ນຖານທາງກົດໝາຍ",
    legalBasisText:
      "ອີງຕາມກົດໝາຍວ່າດ້ວຍຄອບຄົວ ເລກທີ 44/ສພຊ, ລົງວັນທີ 14/06/2018. ວັນທີ່ຂອງການແຈ້ງຈະຖືກກຳນົດອັດຕະໂນມັດເມື່ອສົ່ງຄຳຮ້ອງ.",

    // Parent toggle
    parentDeceasedUnknown: "ພໍ່ແມ່ເສຍຊີວິດ / ບໍ່ຮູ້",
    skipThisSection: "ຂ້າມພາກນີ້",
    statusDeceasedUnknown: "ເສຍຊີວິດ / ບໍ່ຮູ້",

    // Section labels
    secDemographics: "ຂໍ້ມູນປະຊາກອນ (ບໍ່ບັງຄັບ)",
    secCurrentAddressOptional: "ທີ່ຢູ່ປັດຈຸບັນ (ຖ້າມີ)",
    secCurrentAddress: "ທີ່ຢູ່ປັດຈຸບັນ",
    secEducationWork: "ການສຶກສາ ແລະ ການເຮັດວຽກ (ບໍ່ບັງຄັບ)",
    secPlaceOfDeath: "ສະຖານທີ່ເສຍຊີວິດ",
    secTheDeath: "ການເສຍຊີວິດ",
    secAdditionalDetails: "ລາຍລະອຽດເພີ່ມເຕີມ (ບໍ່ບັງຄັບ)",

    // Field labels
    fullName: "ຊື່ ແລະ ນາມສະກຸນ (ລາວ / ອັງກິດ)",
    dobOptional: "ວັນເດືອນປີເກີດ (ບໍ່ບັງຄັບ)",
    dob: "ວັນເດືອນປີເກີດ",
    maritalStatusOptional: "ສະຖານະການແຕ່ງງານ (ບໍ່ບັງຄັບ)",
    maritalStatus: "ສະຖານະການແຕ່ງງານ",
    ethnicity: "ຊົນເຜົ່າ",
    nationality: "ສັນຊາດ",
    ethnicGroup: "ໝວດຊົນເຜົ່າ",
    religion: "ສາສະໜາ",
    censusOrIdOptional: "ເລກປຶ້ມສຳມະໂນຄົວ / ເລກບັດປະຈຳຕົວ (ຖ້າມີ)",
    censusOrId: "ເລກປຶ້ມສຳມະໂນຄົວ / ເລກບັດປະຈຳຕົວ",
    educationLevel: "ລະດັບການສຶກສາ",
    occupation: "ອາຊີບ",
    workplace: "ສະຖານທີ່ເຮັດວຽກ",
    fingerprintCode: "ລະຫັດລາຍນິ້ວມື",
    houseNo: "ເລກທີເຮືອນ",
    gender: "ເພດ",
    dateOfDeath: "ວັນທີເສຍຊີວິດ",
    timeOfDeathOptional: "ເວລາເສຍຊີວິດ (ບໍ່ບັງຄັບ)",
    causeOfDeath: "ສາເຫດການເສຍຊີວິດ",
    causeSpecify: "ສາເຫດ — ກະລຸນາລະບຸ",
    relationshipToDeceased: "ຄວາມສຳພັນກັບຜູ້ເສຍຊີວິດ",
    phoneNumber: "ເບີໂທລະສັບ",
    emailOptional: "ອີເມວ (ບໍ່ບັງຄັບ)",
    villageLabel: "ບ້ານ",

    // Placeholders
    phHouseNo: "ເລກທີເຮືອນ",
    phSelect: "ເລືອກ...",
    phDeceasedName: "ຊື່ ແລະ ນາມສະກຸນຂອງຜູ້ເສຍຊີວິດ",
    phFullName: "ຊື່ ແລະ ນາມສະກຸນ",
    phInformantName: "ຊື່ ແລະ ນາມສະກຸນຂອງຜູ້ແຈ້ງ",
    phOneIdentifier: "ໝາຍເລກໜຶ່ງຢ່າງ + ວັນທີອອກ",
    phOccupation: "ອາຊີບ",
    phWorkplace: "ສະຖານທີ່ເຮັດວຽກ",
    phBiometric: "ລະຫັດຊີວະມິຕິ",
    phTime: "ຊມ:ນທ",
    phSpecifyCause: "ລະບຸສາເຫດ",
    phRelationship: "ເຊັ່ນ: ລູກຊາຍ, ຄູ່ສົມລົດ",
    phPhone: "+856...",
    phEmail: "name@email.com",

    // Review
    reviewWarning:
      "ກະລຸນາກວດສອບຄຳຮ້ອງກ່ອນສົ່ງ. ນາຍບ້ານ ແລະ ຜູ້ແຈ້ງຈະຕ້ອງໄດ້ເຊັນໃບແຈ້ງຢູ່ທີ່ຫ້ອງການບ້ານ.",
    rowProvinceDistrictVillage: "ແຂວງ / ເມືອງ / ບ້ານ",
    rowName: "ຊື່",
    rowGenderDob: "ເພດ / ວັນເກີດ",
    rowPlaceOfDeath: "ສະຖານທີ່ເສຍຊີວິດ",
    rowDateCause: "ວັນທີ / ສາເຫດ",
    rowStatus: "ສະຖານະ",
    rowRelationship: "ຄວາມສຳພັນ",
    rowPhone: "ເບີໂທ",

    // Buttons
    continue: "ສືບຕໍ່",
    submitDeclaration: "ສົ່ງຄຳຮ້ອງ",
    submitting: "ກຳລັງສົ່ງ…",

    // Success
    successTitle: "ສົ່ງໃບແຈ້ງເສຍຊີວິດແລ້ວ!",
    successText:
      "ໄດ້ຮັບຄຳຮ້ອງແລ້ວ. ເມື່ອໄດ້ຮັບການອະນຸມັດ, ຜູ້ເສຍຊີວິດຈະຖືກລົບອອກຈາກບັນທຶກຄອບຄົວ.",
    sumDeceased: "ຜູ້ເສຍຊີວິດ",
    sumDocumentNo: "ເລກທີເອກະສານ",
    sumInformant: "ຜູ້ແຈ້ງ",
    sumFee: "ຄ່າທຳນຽມ",
    sumEstReview: "ຄາດການກວດສອບ",
    sumEstReviewValue: "ບໍ່ເກີນ 5 ວັນລັດຖະການ",
    sumStatus: "ສະຖານະ",
    sumStatusValue: "ສົ່ງແລ້ວ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຄຳຮ້ອງຂອງທ່ານໃນແຖບປະຫວັດ",
    dash: "—",
  },
});
