import { ns } from "../types";

export const divorce = ns({
  en: {
    // Sub-header
    title: "Divorce Certificate",
    subtitle: "Online Application",

    // Steps
    step1Title: "Header",
    step1Subtitle: "Jurisdiction and document details",
    step2Title: "Husband",
    step2Subtitle: "Husband's particulars",
    step3Title: "Wife",
    step3Subtitle: "Wife's particulars",
    step4Title: "Divorce & Registration",
    step4Subtitle: "Basis, date, place and custody",
    step5Title: "Review",
    step5Subtitle: "Check your application",
    step6Title: "Payment",
    step6Subtitle: "Service fee",
    stepOf: "Step {n} of {m}",

    // Document number card
    documentNo: "Document No.",
    autoGenerated: "Auto-generated",

    // Step 1 info
    jurisdictionNote:
      "A voluntary divorce uses a village minute; a contested divorce requires a final People's Court decision. The district registrar registers either route.",

    // Spouse intros
    husbandIntro: "Details of the husband.",
    wifeIntro: "Details of the wife.",

    // Spouse fields
    fullName: "Full Name (Lao / English)",
    fullNamePlaceholder: "Spouse's full name",
    dob: "Date of Birth",
    nationality: "Nationality",
    selectPlaceholder: "Select...",
    idOrPassport: "ID Card / Passport No.",
    idOrPassportPlaceholder: "National ID (Lao) or passport (foreign)",
    currentAddress: "Current address",
    houseNo: "House No.",
    houseNoPlaceholder: "House number",
    villageLabel: "Village",
    marriageCertRef: "Existing Marriage Certificate Ref.",
    marriageCertRefPlaceholder: "Reference of the marriage being dissolved",

    // Nationalities
    natLao: "Lao",
    natThai: "Thai",
    natVietnamese: "Vietnamese",
    natChinese: "Chinese",
    natCambodian: "Cambodian",
    natAmerican: "American",
    natFrench: "French",
    natOther: "Other",

    // Step 4 — divorce basis
    divorceType: "Divorce Type",
    typeVoluntary: "Voluntary",
    typeContested: "Contested",
    minuteLabel: "Minute of divorce (Village Chief)",
    minuteHint: "Village minute for a voluntary divorce",
    courtDecisionLabel: "Court decision",
    courtDecisionHint: "Final People's Court decision",
    dateOfDivorce: "Date of Divorce",
    placeOfRegistration: "Place of Registration",
    placeOfRegistrationPlaceholder: "DoHA office",
    custodyRef: "Children / custody reference (optional)",
    custodyRefPlaceholder: "Custody or dependent arrangements",
    registrationNote:
      "On registration, a separate divorce certificate is issued to each spouse; the registrar applies a protected e-signature in the back office.",

    // Doc upload
    uploadDocument: "Upload document",
    uploadHint: "PDF or image",

    // Step 5 — review
    reviewNote:
      "Please review before submitting. The Head of DoHA approves registration; for a contested divorce the People's Court decision applies.",
    reviewHeader: "Header",
    reviewProvinceDistrictVillage: "Province / District / Village",
    reviewHusband: "Husband",
    reviewWife: "Wife",
    reviewName: "Name",
    reviewIdPassport: "ID / Passport",
    reviewMarriageRef: "Marriage Ref.",
    reviewDivorce: "Divorce & Registration",
    reviewType: "Type",
    reviewDate: "Date of divorce",
    reviewPlace: "Place",
    reviewCustody: "Custody",
    empty: "—",

    // Buttons
    continue: "Continue",
    submitting: "Submitting…",
    pay: "Pay {amount}",

    // Success
    successTitle: "Application Submitted!",
    successBody:
      "Your divorce application has been received. On registration, a certificate is issued to each spouse and marital status is updated.",
    successSpouses: "Spouses",
    successDocumentNo: "Document No.",
    successType: "Type",
    successEstReview: "Est. review",
    successStatus: "Status",
    statusSubmitted: "Submitted",
    backToHome: "Back to Home",
    trackHint: "Track your application in the History tab",

    // Payment
    serviceName: "Divorce Certificate",
  },
  lo: {
    // Sub-header
    title: "ໃບຢັ້ງຢືນການຢ່າຮ້າງ",
    subtitle: "ການຍື່ນຄຳຮ້ອງອອນລາຍ",

    // Steps
    step1Title: "ຂໍ້ມູນທົ່ວໄປ",
    step1Subtitle: "ເຂດອຳນາດ ແລະ ລາຍລະອຽດເອກະສານ",
    step2Title: "ຝ່າຍຊາຍ",
    step2Subtitle: "ຂໍ້ມູນຂອງຝ່າຍຊາຍ",
    step3Title: "ຝ່າຍຍິງ",
    step3Subtitle: "ຂໍ້ມູນຂອງຝ່າຍຍິງ",
    step4Title: "ການຢ່າຮ້າງ ແລະ ການຂຶ້ນທະບຽນ",
    step4Subtitle: "ມູນເຫດ, ວັນທີ, ສະຖານທີ່ ແລະ ການລ້ຽງດູ",
    step5Title: "ກວດສອບ",
    step5Subtitle: "ກວດສອບຄຳຮ້ອງຂອງທ່ານ",
    step6Title: "ການຊຳລະເງິນ",
    step6Subtitle: "ຄ່າທຳນຽມບໍລິການ",
    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // Document number card
    documentNo: "ເລກທີເອກະສານ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",

    // Step 1 info
    jurisdictionNote:
      "ການຢ່າຮ້າງດ້ວຍຄວາມສະໝັກໃຈໃຊ້ບົດບັນທຶກຂັ້ນບ້ານ; ການຢ່າຮ້າງທີ່ມີຂໍ້ຂັດແຍ້ງຕ້ອງມີຄຳຕັດສິນສຸດທ້າຍຂອງສານປະຊາຊົນ. ນາຍທະບຽນຂັ້ນເມືອງເປັນຜູ້ຂຶ້ນທະບຽນທັງສອງກໍລະນີ.",

    // Spouse intros
    husbandIntro: "ຂໍ້ມູນຂອງຝ່າຍຊາຍ.",
    wifeIntro: "ຂໍ້ມູນຂອງຝ່າຍຍິງ.",

    // Spouse fields
    fullName: "ຊື່ ແລະ ນາມສະກຸນ (ລາວ / ອັງກິດ)",
    fullNamePlaceholder: "ຊື່ເຕັມຂອງຄູ່ສົມລົດ",
    dob: "ວັນເດືອນປີເກີດ",
    nationality: "ສັນຊາດ",
    selectPlaceholder: "ເລືອກ...",
    idOrPassport: "ເລກບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ",
    idOrPassportPlaceholder: "ບັດປະຈຳຕົວ (ລາວ) ຫຼື ໜັງສືຜ່ານແດນ (ຕ່າງປະເທດ)",
    currentAddress: "ທີ່ຢູ່ປັດຈຸບັນ",
    houseNo: "ເລກທີເຮືອນ",
    houseNoPlaceholder: "ເລກທີເຮືອນ",
    villageLabel: "ບ້ານ",
    marriageCertRef: "ເລກອ້າງອີງໃບຢັ້ງຢືນການແຕ່ງງານທີ່ມີຢູ່",
    marriageCertRefPlaceholder: "ເລກອ້າງອີງຂອງການແຕ່ງງານທີ່ຈະຍົກເລີກ",

    // Nationalities
    natLao: "ລາວ",
    natThai: "ໄທ",
    natVietnamese: "ຫວຽດນາມ",
    natChinese: "ຈີນ",
    natCambodian: "ກຳປູເຈຍ",
    natAmerican: "ອາເມຣິກາ",
    natFrench: "ຝຣັ່ງ",
    natOther: "ອື່ນໆ",

    // Step 4 — divorce basis
    divorceType: "ປະເພດການຢ່າຮ້າງ",
    typeVoluntary: "ສະໝັກໃຈ",
    typeContested: "ມີຂໍ້ຂັດແຍ້ງ",
    minuteLabel: "ບົດບັນທຶກການຢ່າຮ້າງ (ນາຍບ້ານ)",
    minuteHint: "ບົດບັນທຶກຂັ້ນບ້ານສຳລັບການຢ່າຮ້າງດ້ວຍຄວາມສະໝັກໃຈ",
    courtDecisionLabel: "ຄຳຕັດສິນຂອງສານ",
    courtDecisionHint: "ຄຳຕັດສິນສຸດທ້າຍຂອງສານປະຊາຊົນ",
    dateOfDivorce: "ວັນທີຢ່າຮ້າງ",
    placeOfRegistration: "ສະຖານທີ່ຂຶ້ນທະບຽນ",
    placeOfRegistrationPlaceholder: "ຫ້ອງການ ພະແນກພາຍໃນ",
    custodyRef: "ບຸດ / ການອ້າງອີງສິດລ້ຽງດູ (ບໍ່ບັງຄັບ)",
    custodyRefPlaceholder: "ການຈັດການສິດລ້ຽງດູ ຫຼື ຜູ້ຢູ່ໃນອຸປະຖຳ",
    registrationNote:
      "ເມື່ອຂຶ້ນທະບຽນແລ້ວ, ຈະອອກໃບຢັ້ງຢືນການຢ່າຮ້າງໃຫ້ແຕ່ລະຝ່າຍ; ນາຍທະບຽນຈະລົງລາຍເຊັນເອເລັກໂຕຣນິກທີ່ໄດ້ຮັບການປ້ອງກັນຢູ່ຫ້ອງການຫຼັງ.",

    // Doc upload
    uploadDocument: "ອັບໂຫຼດເອກະສານ",
    uploadHint: "PDF ຫຼື ຮູບພາບ",

    // Step 5 — review
    reviewNote:
      "ກະລຸນາກວດສອບກ່ອນຍື່ນ. ຫົວໜ້າພະແນກພາຍໃນເປັນຜູ້ອະນຸມັດການຂຶ້ນທະບຽນ; ສຳລັບການຢ່າຮ້າງທີ່ມີຂໍ້ຂັດແຍ້ງໃຫ້ໃຊ້ຄຳຕັດສິນຂອງສານປະຊາຊົນ.",
    reviewHeader: "ຂໍ້ມູນທົ່ວໄປ",
    reviewProvinceDistrictVillage: "ແຂວງ / ເມືອງ / ບ້ານ",
    reviewHusband: "ຝ່າຍຊາຍ",
    reviewWife: "ຝ່າຍຍິງ",
    reviewName: "ຊື່",
    reviewIdPassport: "ບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ",
    reviewMarriageRef: "ເລກອ້າງອີງການແຕ່ງງານ",
    reviewDivorce: "ການຢ່າຮ້າງ ແລະ ການຂຶ້ນທະບຽນ",
    reviewType: "ປະເພດ",
    reviewDate: "ວັນທີຢ່າຮ້າງ",
    reviewPlace: "ສະຖານທີ່",
    reviewCustody: "ສິດລ້ຽງດູ",
    empty: "—",

    // Buttons
    continue: "ສືບຕໍ່",
    submitting: "ກຳລັງຍື່ນ…",
    pay: "ຊຳລະ {amount}",

    // Success
    successTitle: "ຍື່ນຄຳຮ້ອງສຳເລັດ!",
    successBody:
      "ຄຳຮ້ອງຂໍຢ່າຮ້າງຂອງທ່ານໄດ້ຮັບແລ້ວ. ເມື່ອຂຶ້ນທະບຽນແລ້ວ ຈະອອກໃບຢັ້ງຢືນໃຫ້ແຕ່ລະຝ່າຍ ແລະ ປັບປຸງສະຖານະການສົມລົດ.",
    successSpouses: "ຄູ່ສົມລົດ",
    successDocumentNo: "ເລກທີເອກະສານ",
    successType: "ປະເພດ",
    successEstReview: "ໄລຍະກວດສອບໂດຍປະມານ",
    successStatus: "ສະຖານະ",
    statusSubmitted: "ຍື່ນແລ້ວ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຄຳຮ້ອງຂອງທ່ານໄດ້ທີ່ແຖບປະຫວັດ",

    // Payment
    serviceName: "ໃບຢັ້ງຢືນການຢ່າຮ້າງ",
  },
});
