import { ns } from "../types";

export const divorce = ns({
  en: {
    // Sub-header
    title: "Divorce Certificate",
    subtitle: "Online Application",

    // Steps
    step1Title: "Divorce basis",
    step1Subtitle: "Type, mediation record or court decree",
    step2Title: "Husband",
    step2Subtitle: "Husband's particulars",
    step3Title: "Wife",
    step3Subtitle: "Wife's particulars",
    step4Title: "Registration & documents",
    step4Subtitle: "Date, place and supporting documents",
    step5Title: "Review",
    step5Subtitle: "Check your application",
    step6Title: "Payment",
    step6Subtitle: "Service fee",
    stepOf: "Step {n} of {m}",

    // Document number card
    documentNo: "Document No.",
    autoGenerated: "Auto-generated",

    // Step 1 info
    jurisdictionNote:
      "A voluntary divorce uses a village minute; a contested divorce requires a final People's Court decision. The district registrar registers either route.",

    // ── Step 1 — Basis & mediation record (FR-11) ──
    basisTypeNote:
      "Choose the divorce type. A voluntary divorce links a village mediation record; a contested divorce uses a final People's Court decree.",
    mediationChooseNote:
      "A voluntary divorce registration starts from a mediation record. Link an existing record, or create one first.",
    mediationSelectExisting: "Select an existing mediation record",
    mediationSelectExistingHint: "Link a recorded mediation and pre-fill the spouses' details",
    mediationCreateNew: "Create a new mediation record",
    mediationCreateNewHint: "Capture the mediation first, then continue to registration",
    mediationChooseRequired: "Please choose an option to continue",
    mediationBack: "Back to options",
    mediationPickTitle: "Choose a mediation record",
    mediationPickRequired: "Please select a mediation record",
    mediationLinkedTitle: "Mediation record linked",
    mediationRecordNo: "Mediation record No.",
    mediationCouple: "Spouses",
    mediationWhere: "Location",
    mediationDate: "Date",
    mediationChange: "Change record",
    mediationPrefillNote:
      "The spouses' shared details have been pre-filled from the mediation record — review them in the next steps.",
    mediationNoLabel: "Mediation record No.",
    mediationNewNote:
      "The mediation record is signed by both spouses (thumbprints), witnesses and the Village Chief; registration follows at the district.",
    mediationWitnesses: "Witnesses",
    dateMarriageBegan: "Date the marriage began",
    reasonsHusband: "Reasons for divorce — husband",
    reasonsWife: "Reasons for divorce — wife",
    reasonsPlaceholder: "State the reasons",
    mediationOutcome: "Outcome of mediation",
    mediationOutcomePlaceholder: "Result of the mediation attempt",
    divisionSection: "Division of property, debts & custody",
    propertyDivision: "Property division",
    propertyDivisionPlaceholder: "How joint property is divided (husband / wife / children)",
    debts: "Agreement on debts (optional)",
    debtsPlaceholder: "How household debts are divided",
    additionalAssets: "Additional / separate assets (optional)",
    additionalAssetsPlaceholder: "Separate assets outside the joint estate",
    hasChildren: "The couple has children",
    hasChildrenHint: "Record the children and the custody agreement",
    childrenList: "Children (names & ages)",
    childrenListPlaceholder: "List the children born to the marriage",
    custodyAgreement: "Child custody agreement",
    custodyAgreementPlaceholder: "Care, visitation and support per child",
    contestedNote:
      "A contested divorce is decided by the People's Court. Attach the final court decree; the Head of DoHA approves registration.",
    courtName: "People's Court",
    courtNamePlaceholder: "Name of the deciding court",
    courtDecisionDate: "Court decision date",
    witnessName: "Name",
    witnessNamePlaceholder: "Witness full name",

    // ── Step 4 — Registration documents ──
    registrationDocsNote: "Attach the required supporting documents for registration.",
    householdBook: "Household registration book",
    guaranteeCert: "Guarantee certificate",
    guaranteeCertHint: "Guarantor's certificate",
    photos3x4: "3×4 photos (2 each)",
    photos3x4Hint: "Recent photos of each spouse • image or PDF",
    reviewBasis: "Divorce basis",
    reviewCourtDecision: "Court",
    reviewRegistration: "Registration",

    // Spouse intros
    husbandIntro: "Details of the husband.",
    wifeIntro: "Details of the wife.",

    // Spouse fields
    fullName: "Full Name (Lao / English)",
    fullNamePlaceholder: "Spouse's full name",
    dob: "Date of Birth",
    nationality: "Nationality",
    selectPlaceholder: "Select...",
    idOrPassport: "ID Card / Passport No.",
    idOrPassportPlaceholder: "National ID (Lao) or passport (foreign)",
    currentAddress: "Current address",
    houseNo: "House No.",
    houseNoPlaceholder: "House number",
    villageLabel: "Village",
    marriageCertRef: "Existing Marriage Certificate Ref.",
    marriageCertRefPlaceholder: "Reference of the marriage being dissolved",

    // Nationalities
    natLao: "Lao",
    natThai: "Thai",
    natVietnamese: "Vietnamese",
    natChinese: "Chinese",
    natCambodian: "Cambodian",
    natAmerican: "American",
    natFrench: "French",
    natOther: "Other",

    // Step 4 — divorce basis
    divorceType: "Divorce Type",
    typeVoluntary: "Voluntary",
    typeContested: "Contested",
    minuteLabel: "Minute of divorce (Village Chief)",
    minuteHint: "Village minute for a voluntary divorce",
    courtDecisionLabel: "Court decision",
    courtDecisionHint: "Final People's Court decision",
    dateOfDivorce: "Date of Divorce",
    placeOfRegistration: "Place of Registration",
    placeOfRegistrationPlaceholder: "DoHA office",
    custodyRef: "Children / custody reference (optional)",
    custodyRefPlaceholder: "Custody or dependent arrangements",
    registrationNote:
      "On registration, a separate divorce certificate is issued to each spouse; the registrar applies a protected e-signature in the back office.",

    // Doc upload
    uploadDocument: "Upload document",
    uploadHint: "PDF or image",

    // Step 5 — review
    reviewNote:
      "Please review before submitting. The Head of DoHA approves registration; for a contested divorce the People's Court decision applies.",
    reviewHeader: "Header",
    reviewProvinceDistrictVillage: "Province / District / Village",
    reviewHusband: "Husband",
    reviewWife: "Wife",
    reviewName: "Name",
    reviewIdPassport: "ID / Passport",
    reviewMarriageRef: "Marriage Ref.",
    reviewDivorce: "Divorce & Registration",
    reviewType: "Type",
    reviewDate: "Date of divorce",
    reviewPlace: "Place",
    reviewCustody: "Custody",
    empty: "—",

    // Buttons
    continue: "Continue",
    submitting: "Submitting…",
    pay: "Pay {amount}",

    // Success
    successTitle: "Application Submitted!",
    successBody:
      "Your divorce application has been received. On registration, a certificate is issued to each spouse and marital status is updated.",
    successSpouses: "Spouses",
    successDocumentNo: "Document No.",
    successType: "Type",
    successEstReview: "Est. review",
    successStatus: "Status",
    statusSubmitted: "Submitted",
    backToHome: "Back to Home",
    trackHint: "Track your application in the History tab",

    // Payment
    serviceName: "Divorce Certificate",
  },
  lo: {
    // Sub-header
    title: "ໃບຢັ້ງຢືນການຢ່າຮ້າງ",
    subtitle: "ການຍື່ນຄຳຮ້ອງອອນລາຍ",

    // Steps
    step1Title: "ມູນເຫດການຢ່າຮ້າງ",
    step1Subtitle: "ປະເພດ, ບົດບັນທຶກການໄກ່ເກ່ຍ ຫຼື ຄຳຕັດສິນຂອງສານ",
    step2Title: "ຝ່າຍຊາຍ",
    step2Subtitle: "ຂໍ້ມູນຂອງຝ່າຍຊາຍ",
    step3Title: "ຝ່າຍຍິງ",
    step3Subtitle: "ຂໍ້ມູນຂອງຝ່າຍຍິງ",
    step4Title: "ການຂຶ້ນທະບຽນ ແລະ ເອກະສານ",
    step4Subtitle: "ວັນທີ, ສະຖານທີ່ ແລະ ເອກະສານປະກອບ",
    step5Title: "ກວດສອບ",
    step5Subtitle: "ກວດສອບຄຳຮ້ອງຂອງທ່ານ",
    step6Title: "ການຊຳລະເງິນ",
    step6Subtitle: "ຄ່າທຳນຽມບໍລິການ",
    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // Document number card
    documentNo: "ເລກທີເອກະສານ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",

    // Step 1 info
    jurisdictionNote:
      "ການຢ່າຮ້າງດ້ວຍຄວາມສະໝັກໃຈໃຊ້ບົດບັນທຶກຂັ້ນບ້ານ; ການຢ່າຮ້າງທີ່ມີຂໍ້ຂັດແຍ້ງຕ້ອງມີຄຳຕັດສິນສຸດທ້າຍຂອງສານປະຊາຊົນ. ນາຍທະບຽນຂັ້ນເມືອງຈະເປັນຜູ້ຂຶ້ນທະບຽນທັງສອງກໍລະນີ.",

    // ── Step 1 — Basis & mediation record (FR-11) ──
    basisTypeNote:
      "ເລືອກປະເພດການຢ່າຮ້າງ. ການຢ່າຮ້າງດ້ວຍຄວາມສະໝັກໃຈຈະເຊື່ອມໂຍງບົດບັນທຶກການໄກ່ເກ່ຍຂັ້ນບ້ານ; ການຢ່າຮ້າງທີ່ມີຂໍ້ຂັດແຍ້ງໃຊ້ຄຳຕັດສິນສຸດທ້າຍຂອງສານປະຊາຊົນ.",
    mediationChooseNote:
      "ການຂຶ້ນທະບຽນການຢ່າຮ້າງດ້ວຍຄວາມສະໝັກໃຈເລີ່ມຈາກບົດບັນທຶກການໄກ່ເກ່ຍ. ເຊື່ອມໂຍງບົດບັນທຶກທີ່ມີຢູ່ ຫຼື ສ້າງໃໝ່ກ່ອນ.",
    mediationSelectExisting: "ເລືອກບົດບັນທຶກການໄກ່ເກ່ຍທີ່ມີຢູ່",
    mediationSelectExistingHint: "ເຊື່ອມໂຍງບົດບັນທຶກທີ່ບັນທຶກໄວ້ ແລະ ຕື່ມຂໍ້ມູນຄູ່ສົມລົດໃຫ້ອັດຕະໂນມັດ",
    mediationCreateNew: "ສ້າງບົດບັນທຶກການໄກ່ເກ່ຍໃໝ່",
    mediationCreateNewHint: "ບັນທຶກການໄກ່ເກ່ຍກ່ອນ ແລ້ວຈຶ່ງໄປການຂຶ້ນທະບຽນ",
    mediationChooseRequired: "ກະລຸນາເລືອກໜຶ່ງທາງເລືອກເພື່ອດຳເນີນຕໍ່",
    mediationBack: "ກັບໄປທາງເລືອກ",
    mediationPickTitle: "ເລືອກບົດບັນທຶກການໄກ່ເກ່ຍ",
    mediationPickRequired: "ກະລຸນາເລືອກບົດບັນທຶກການໄກ່ເກ່ຍ",
    mediationLinkedTitle: "ເຊື່ອມໂຍງບົດບັນທຶກແລ້ວ",
    mediationRecordNo: "ເລກບົດບັນທຶກການໄກ່ເກ່ຍ",
    mediationCouple: "ຄູ່ສົມລົດ",
    mediationWhere: "ສະຖານທີ",
    mediationDate: "ວັນທີ",
    mediationChange: "ປ່ຽນບົດບັນທຶກ",
    mediationPrefillNote:
      "ຂໍ້ມູນຮ່ວມຂອງຄູ່ສົມລົດຖືກຕື່ມຈາກບົດບັນທຶກການໄກ່ເກ່ຍແລ້ວ — ກະລຸນາກວດຄືນໃນຂັ້ນຕອນຕໍ່ໄປ.",
    mediationNoLabel: "ເລກບົດບັນທຶກການໄກ່ເກ່ຍ",
    mediationNewNote:
      "ບົດບັນທຶກການໄກ່ເກ່ຍນີ້ເຊັນໂດຍຄູ່ສົມລົດທັງສອງ (ລາຍໂປ້ມື), ພະຍານ ແລະ ນາຍບ້ານ; ການຂຶ້ນທະບຽນຈະຕໍ່ໄປຢູ່ຂັ້ນເມືອງ.",
    mediationWitnesses: "ພະຍານ",
    dateMarriageBegan: "ວັນທີເລີ່ມເປັນຄອບຄົວ",
    reasonsHusband: "ສາເຫດການຢ່າຮ້າງ — ຝ່າຍຊາຍ",
    reasonsWife: "ສາເຫດການຢ່າຮ້າງ — ຝ່າຍຍິງ",
    reasonsPlaceholder: "ລະບຸສາເຫດ",
    mediationOutcome: "ຜົນການໄກ່ເກ່ຍ",
    mediationOutcomePlaceholder: "ຜົນຂອງການໄກ່ເກ່ຍ",
    divisionSection: "ການແບ່ງຊັບສິນ, ໜີ້ສິນ ແລະ ການລ້ຽງດູ",
    propertyDivision: "ການແບ່ງຊັບສິນ",
    propertyDivisionPlaceholder: "ວິທີແບ່ງຊັບສິນຮ່ວມ (ຝ່າຍຊາຍ / ຝ່າຍຍິງ / ລູກ)",
    debts: "ຂໍ້ຕົກລົງເລື່ອງໜີ້ສິນ (ບໍ່ບັງຄັບ)",
    debtsPlaceholder: "ວິທີແບ່ງໜີ້ສິນຄອບຄົວ",
    additionalAssets: "ຊັບສິນເພີ່ມ / ສ່ວນຕົວ (ບໍ່ບັງຄັບ)",
    additionalAssetsPlaceholder: "ຊັບສິນສ່ວນຕົວນອກຈາກຊັບສິນຮ່ວມ",
    hasChildren: "ຄູ່ສົມລົດມີລູກ",
    hasChildrenHint: "ບັນທຶກລາຍຊື່ລູກ ແລະ ຂໍ້ຕົກລົງການລ້ຽງດູ",
    childrenList: "ລູກ (ຊື່ ແລະ ອາຍຸ)",
    childrenListPlaceholder: "ລະບຸລາຍຊື່ລູກທີ່ເກີດໃນການແຕ່ງງານ",
    custodyAgreement: "ຂໍ້ຕົກລົງການລ້ຽງດູລູກ",
    custodyAgreementPlaceholder: "ການດູແລ, ການຢ້ຽມຢາມ ແລະ ການອຸປະຖຳຕໍ່ລູກແຕ່ລະຄົນ",
    contestedNote:
      "ການຢ່າຮ້າງທີ່ມີຂໍ້ຂັດແຍ້ງຕັດສິນໂດຍສານປະຊາຊົນ. ກະລຸນາແນບຄຳຕັດສິນສຸດທ້າຍຂອງສານ; ຫົວໜ້າພະແນກພາຍໃນເປັນຜູ້ອະນຸມັດການຂຶ້ນທະບຽນ.",
    courtName: "ສານປະຊາຊົນ",
    courtNamePlaceholder: "ຊື່ຂອງສານທີ່ຕັດສິນ",
    courtDecisionDate: "ວັນທີຄຳຕັດສິນຂອງສານ",
    witnessName: "ຊື່",
    witnessNamePlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງພະຍານ",

    // ── Step 4 — Registration documents ──
    registrationDocsNote: "ກະລຸນາແນບເອກະສານປະກອບທີ່ຕ້ອງການສຳລັບການຂຶ້ນທະບຽນ.",
    householdBook: "ປຶ້ມສຳມະໂນຄົວ",
    guaranteeCert: "ໃບຢັ້ງຢືນຮັບປະກັນ",
    guaranteeCertHint: "ໃບຢັ້ງຢືນຂອງຜູ້ຮັບປະກັນ",
    photos3x4: "ຮູບ 3×4 (ຝ່າຍລະ 2 ໃບ)",
    photos3x4Hint: "ຮູບຫຼ້າສຸດຂອງແຕ່ລະຝ່າຍ • ຮູບພາບ ຫຼື PDF",
    reviewBasis: "ມູນເຫດການຢ່າຮ້າງ",
    reviewCourtDecision: "ສານ",
    reviewRegistration: "ການຂຶ້ນທະບຽນ",

    // Spouse intros
    husbandIntro: "ຂໍ້ມູນຂອງຝ່າຍຊາຍ.",
    wifeIntro: "ຂໍ້ມູນຂອງຝ່າຍຍິງ.",

    // Spouse fields
    fullName: "ຊື່ ແລະ ນາມສະກຸນ (ລາວ / ອັງກິດ)",
    fullNamePlaceholder: "ຊື່ເຕັມຂອງຄູ່ສົມລົດ",
    dob: "ວັນເດືອນປີເກີດ",
    nationality: "ສັນຊາດ",
    selectPlaceholder: "ເລືອກ...",
    idOrPassport: "ເລກບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ",
    idOrPassportPlaceholder: "ບັດປະຈຳຕົວ (ລາວ) ຫຼື ໜັງສືຜ່ານແດນ (ຕ່າງປະເທດ)",
    currentAddress: "ທີ່ຢູ່ປັດຈຸບັນ",
    houseNo: "ເລກທີເຮືອນ",
    houseNoPlaceholder: "ເລກທີເຮືອນ",
    villageLabel: "ບ້ານ",
    marriageCertRef: "ເລກອ້າງອີງໃບຢັ້ງຢືນການແຕ່ງງານທີ່ມີຢູ່",
    marriageCertRefPlaceholder: "ເລກອ້າງອີງຂອງການແຕ່ງງານທີ່ຈະຍົກເລີກ",

    // Nationalities
    natLao: "ລາວ",
    natThai: "ໄທ",
    natVietnamese: "ຫວຽດນາມ",
    natChinese: "ຈີນ",
    natCambodian: "ກຳປູເຈຍ",
    natAmerican: "ອາເມຣິກາ",
    natFrench: "ຝຣັ່ງ",
    natOther: "ອື່ນໆ",

    // Step 4 — divorce basis
    divorceType: "ປະເພດການຢ່າຮ້າງ",
    typeVoluntary: "ສະໝັກໃຈ",
    typeContested: "ມີຂໍ້ຂັດແຍ້ງ",
    minuteLabel: "ບົດບັນທຶກການຢ່າຮ້າງ (ນາຍບ້ານ)",
    minuteHint: "ບົດບັນທຶກຂັ້ນບ້ານສຳລັບການຢ່າຮ້າງດ້ວຍຄວາມສະໝັກໃຈ",
    courtDecisionLabel: "ຄຳຕັດສິນຂອງສານ",
    courtDecisionHint: "ຄຳຕັດສິນສຸດທ້າຍຂອງສານປະຊາຊົນ",
    dateOfDivorce: "ວັນທີຢ່າຮ້າງ",
    placeOfRegistration: "ສະຖານທີ່ຂຶ້ນທະບຽນ",
    placeOfRegistrationPlaceholder: "ຫ້ອງການ ພະແນກພາຍໃນ",
    custodyRef: "ບຸດ / ການອ້າງອີງສິດລ້ຽງດູ (ບໍ່ບັງຄັບ)",
    custodyRefPlaceholder: "ການຈັດການສິດລ້ຽງດູ ຫຼື ຜູ້ຢູ່ໃນອຸປະຖຳ",
    registrationNote:
      "ເມື່ອຂຶ້ນທະບຽນແລ້ວ, ຈະອອກໃບຢັ້ງຢືນການຢ່າຮ້າງໃຫ້ແຕ່ລະຝ່າຍ; ນາຍທະບຽນຈະລົງລາຍເຊັນເອເລັກໂຕຣນິກທີ່ໄດ້ຮັບການປ້ອງກັນຢູ່ຫ້ອງການຫຼັງ.",

    // Doc upload
    uploadDocument: "ອັບໂຫຼດເອກະສານ",
    uploadHint: "PDF ຫຼື ຮູບພາບ",

    // Step 5 — review
    reviewNote:
      "ກະລຸນາກວດສອບຄືນກ່ອນຍື່ນ. ຫົວໜ້າພະແນກພາຍໃນຈະເປັນຜູ້ອະນຸມັດການຂຶ້ນທະບຽນ; ສຳລັບການຢ່າຮ້າງທີ່ມີຂໍ້ຂັດແຍ້ງໃຫ້ໃຊ້ຄຳຕັດສິນຂອງສານປະຊາຊົນເປັນທີ່ສິ້ນສຸດ.",
    reviewHeader: "ຂໍ້ມູນທົ່ວໄປ",
    reviewProvinceDistrictVillage: "ແຂວງ / ເມືອງ / ບ້ານ",
    reviewHusband: "ຝ່າຍຊາຍ",
    reviewWife: "ຝ່າຍຍິງ",
    reviewName: "ຊື່",
    reviewIdPassport: "ບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ",
    reviewMarriageRef: "ເລກອ້າງອີງການແຕ່ງງານ",
    reviewDivorce: "ການຢ່າຮ້າງ ແລະ ການຂຶ້ນທະບຽນ",
    reviewType: "ປະເພດ",
    reviewDate: "ວັນທີຢ່າຮ້າງ",
    reviewPlace: "ສະຖານທີ່",
    reviewCustody: "ສິດລ້ຽງດູ",
    empty: "—",

    // Buttons
    continue: "ສືບຕໍ່",
    submitting: "ກຳລັງຍື່ນ…",
    pay: "ຊຳລະ {amount}",

    // Success
    successTitle: "ຍື່ນຄຳຮ້ອງສຳເລັດ!",
    successBody:
      "ໄດ້ຮັບຄຳຮ້ອງຂໍຢ່າຮ້າງຂອງທ່ານແລ້ວ. ເມື່ອຂຶ້ນທະບຽນແລ້ວຈະມີການອອກໃບຢັ້ງຢືນໃຫ້ແຕ່ລະຝ່າຍ ແລະ ປັບປຸງສະຖານະການສົມລົດ.",
    successSpouses: "ຄູ່ສົມລົດ",
    successDocumentNo: "ເລກທີເອກະສານ",
    successType: "ປະເພດ",
    successEstReview: "ໄລຍະກວດສອບໂດຍປະມານ",
    successStatus: "ສະຖານະ",
    statusSubmitted: "ຍື່ນແລ້ວ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຄຳຮ້ອງຂອງທ່ານໄດ້ທີ່ແຖບປະຫວັດ",

    // Payment
    serviceName: "ໃບຢັ້ງຢືນການຢ່າຮ້າງ",
  },
});
