import { ns } from "../types";

export const familyBook = ns({
  en: {
    // Header
    title: "Family Book",
    subtitle: "Household Registration",

    // Steps
    step1Label: "Household",
    step1Subtitle: "Cover and household head",
    step2Label: "Members",
    step2Subtitle: "People registered in the household",
    step3Label: "Review",
    step3Subtitle: "Check and submit the record",
    stepOf: "Step {n} of {m}",

    // Genders / nationalities / ethnicities
    genderFemale: "Female",
    genderMale: "Male",
    natLao: "Lao",
    natThai: "Thai",
    natVietnamese: "Vietnamese",
    natChinese: "Chinese",
    natCambodian: "Cambodian",
    natOther: "Other",
    ethLao: "Lao",
    ethKhmu: "Khmu",
    ethHmong: "Hmong",
    ethPhouthai: "Phouthai",
    ethTai: "Tai",
    ethOther: "Other",

    // Relationships
    relHead: "Household Head",
    relSpouse: "Spouse",
    relChild: "Child",
    relParent: "Parent",
    relSibling: "Sibling",
    relGrandparent: "Grandparent",
    relGrandchild: "Grandchild",
    relOther: "Other",

    // Family book number block
    familyBookNo: "Family Book No.",
    autoGenerated: "Auto-generated",

    // Step 1 — Household & Head
    holderNameLabel: "Holder's Name (Book Cover)",
    holderNamePlaceholder: "Name shown on the book cover",
    householdHead: "Household head",
    nameAndSurname: "Name and Surname",
    holderFullNamePlaceholder: "Full name of the household head",
    idCardNo: "ID Card No.",
    idCardNoPlaceholder: "National ID number",
    placeOfBirth: "Place of Birth",
    placeOfBirthPlaceholder: "Town / village",
    unit: "Unit",
    unitPlaceholder: "Unit no.",
    group: "Group",
    groupPlaceholder: "Group no.",
    address: "Address",
    dateOfIssue: "Date of Issue",
    setOnIssuance: "Set on issuance",

    // Step 2 — Members
    person: "person",
    people: "people",
    menCount: "{n} men",
    womenCount: "{n} women",
    memberN: "Member {n}",
    memberFullNamePlaceholder: "Full name",
    gender: "Gender",
    selectPlaceholder: "Select...",
    dateOfBirth: "Date of Birth",
    relationshipToHead: "Relationship to Head",
    nationality: "Nationality",
    ethnicityOptional: "Ethnicity (optional)",
    uinNote: "UIN — assigned automatically on registration",
    addMember: "Add member",

    // Step 3 — Review
    reviewNotice:
      "Please review the household record before submitting. The record is maintained by DoPS and updated automatically as life events are registered.",
    household: "Household",
    holder: "Holder",
    unitGroup: "Unit / Group",
    peopleLabel: "People",
    fee: "Fee",
    members: "Members",
    peopleSummary: "{total} ({men}M / {women}F)",

    // Bottom CTA
    submitting: "Submitting…",
    submitRecord: "Submit Record",
    continue: "Continue",

    // Success
    successTitle: "Household Record Submitted!",
    successBody:
      "The family book record has been received. A UIN is assigned to each member and the record is maintained by DoPS.",
    successHead: "Household head",
    successMembers: "Members",
    statusLabel: "Status",
    statusSubmitted: "Submitted",
    backToHome: "Back to Home",
    trackHint: "Track your record in the History tab",
  },
  lo: {
    // Header
    title: "ປຶ້ມສຳມະໂນຄົວ",
    subtitle: "ການລົງທະບຽນສຳມະໂນຄົວ",

    // Steps
    step1Label: "ສຳມະໂນຄົວ",
    step1Subtitle: "ໜ້າປົກ ແລະ ຫົວໜ້າຄອບຄົວ",
    step2Label: "ສະມາຊິກ",
    step2Subtitle: "ບຸກຄົນທີ່ລົງທະບຽນໃນສຳມະໂນຄົວ",
    step3Label: "ກວດທານ",
    step3Subtitle: "ກວດທານ ແລະ ສົ່ງຂໍ້ມູນ",
    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // Genders / nationalities / ethnicities
    genderFemale: "ຍິງ",
    genderMale: "ຊາຍ",
    natLao: "ລາວ",
    natThai: "ໄທ",
    natVietnamese: "ຫວຽດນາມ",
    natChinese: "ຈີນ",
    natCambodian: "ກຳປູເຈຍ",
    natOther: "ອື່ນໆ",
    ethLao: "ລາວ",
    ethKhmu: "ຂະມຸ",
    ethHmong: "ມົ້ງ",
    ethPhouthai: "ຜູ້ໄທ",
    ethTai: "ໄຕ",
    ethOther: "ອື່ນໆ",

    // Relationships
    relHead: "ຫົວໜ້າຄອບຄົວ",
    relSpouse: "ຄູ່ສົມລົດ",
    relChild: "ລູກ",
    relParent: "ພໍ່ແມ່",
    relSibling: "ອ້າຍເອື້ອຍນ້ອງ",
    relGrandparent: "ປູ່ຍ່າຕາຍາຍ",
    relGrandchild: "ຫຼານ",
    relOther: "ອື່ນໆ",

    // Family book number block
    familyBookNo: "ເລກປຶ້ມສຳມະໂນຄົວ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",

    // Step 1 — Household & Head
    holderNameLabel: "ຊື່ຜູ້ຖືປຶ້ມ (ໜ້າປົກ)",
    holderNamePlaceholder: "ຊື່ທີ່ສະແດງຢູ່ໜ້າປົກປຶ້ມ",
    householdHead: "ຫົວໜ້າຄອບຄົວ",
    nameAndSurname: "ຊື່ ແລະ ນາມສະກຸນ",
    holderFullNamePlaceholder: "ຊື່ເຕັມຂອງຫົວໜ້າຄອບຄົວ",
    idCardNo: "ເລກບັດປະຈຳຕົວ",
    idCardNoPlaceholder: "ເລກບັດປະຈຳຕົວແຫ່ງຊາດ",
    placeOfBirth: "ສະຖານທີ່ເກີດ",
    placeOfBirthPlaceholder: "ເມືອງ / ບ້ານ",
    unit: "ໜ່ວຍ",
    unitPlaceholder: "ເລກໜ່ວຍ",
    group: "ກຸ່ມ",
    groupPlaceholder: "ເລກກຸ່ມ",
    address: "ທີ່ຢູ່",
    dateOfIssue: "ວັນທີອອກໃຫ້",
    setOnIssuance: "ກຳນົດເມື່ອອອກໃຫ້",

    // Step 2 — Members
    person: "ຄົນ",
    people: "ຄົນ",
    menCount: "ຊາຍ {n} ຄົນ",
    womenCount: "ຍິງ {n} ຄົນ",
    memberN: "ສະມາຊິກ {n}",
    memberFullNamePlaceholder: "ຊື່ເຕັມ",
    gender: "ເພດ",
    selectPlaceholder: "ເລືອກ...",
    dateOfBirth: "ວັນເດືອນປີເກີດ",
    relationshipToHead: "ຄວາມສຳພັນກັບຫົວໜ້າຄອບຄົວ",
    nationality: "ສັນຊາດ",
    ethnicityOptional: "ຊົນເຜົ່າ (ບໍ່ບັງຄັບ)",
    uinNote: "UIN — ກຳນົດອັດຕະໂນມັດເມື່ອລົງທະບຽນ",
    addMember: "ເພີ່ມສະມາຊິກ",

    // Step 3 — Review
    reviewNotice:
      "ກະລຸນາກວດທານຂໍ້ມູນສຳມະໂນຄົວກ່ອນສົ່ງ. ຂໍ້ມູນຖືກຮັກສາໂດຍ ກົມຕຳຫຼວດ ແລະ ປັບປຸງອັດຕະໂນມັດເມື່ອມີການລົງທະບຽນເຫດການຊີວິດ.",
    household: "ສຳມະໂນຄົວ",
    holder: "ຜູ້ຖືປຶ້ມ",
    unitGroup: "ໜ່ວຍ / ກຸ່ມ",
    peopleLabel: "ຈຳນວນຄົນ",
    fee: "ຄ່າທຳນຽມ",
    members: "ສະມາຊິກ",
    peopleSummary: "{total} (ຊ {men} / ຍ {women})",

    // Bottom CTA
    submitting: "ກຳລັງສົ່ງ…",
    submitRecord: "ສົ່ງຂໍ້ມູນ",
    continue: "ສືບຕໍ່",

    // Success
    successTitle: "ສົ່ງຂໍ້ມູນສຳມະໂນຄົວສຳເລັດ!",
    successBody:
      "ໄດ້ຮັບຂໍ້ມູນປຶ້ມສຳມະໂນຄົວແລ້ວ. ສະມາຊິກແຕ່ລະຄົນຈະໄດ້ຮັບ UIN ແລະ ຂໍ້ມູນຖືກຮັກສາໂດຍ ກົມຕຳຫຼວດ.",
    successHead: "ຫົວໜ້າຄອບຄົວ",
    successMembers: "ສະມາຊິກ",
    statusLabel: "ສະຖານະ",
    statusSubmitted: "ສົ່ງແລ້ວ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຂໍ້ມູນຂອງທ່ານໃນແຖບ ປະຫວັດ",
  },
});
