import { ns } from "../types";

export const marriage = ns({
  en: {
    // ── Header / sub-header ──
    title: "Marriage Certificate",
    subtitle: "Online Application",
    serviceName: "Marriage Certificate",

    // ── Step labels & subtitles ──
    step1Title: "Header",
    step1Subtitle: "Jurisdiction and document details",
    step2Title: "Spouse A",
    step2Subtitle: "First spouse's particulars",
    step3Title: "Spouse B",
    step3Subtitle: "Second spouse's particulars",
    step4Title: "Documents",
    step4Subtitle: "Supporting documents for the couple",
    step5Title: "Registration",
    step5Subtitle: "Date, place and witnesses",
    step6Title: "Review",
    step6Subtitle: "Check your application",
    step7Title: "Payment",
    step7Subtitle: "Service fee",
    stepOf: "Step {n} of {m}",

    // ── Step 1 — Header ──
    documentNo: "Document No.",
    autoGenerated: "Auto-generated",
    headerNote:
      "The application is certified by the Village Chief, then reviewed and registered at the district office before 3 witnesses.",

    // ── Step 2 / 3 intros ──
    spouseAIntro: "Details of the first spouse.",
    spouseBIntro: "Details of the second spouse.",

    // ── Spouse fields ──
    fullName: "Full Name (Lao / English)",
    fullNamePh: "Spouse's full name",
    dob: "Date of Birth",
    gender: "Gender",
    selectPh: "Select...",
    nationality: "Nationality",
    idOrPassport: "ID Card / Passport No.",
    idOrPassportPh: "National ID (Lao) or passport (foreign)",
    currentAddress: "Current address",
    houseNo: "House No.",
    houseNoPh: "House number",
    village: "Village",
    residenceCertRef: "Residence Certificate Ref.",
    residenceCertRefPh: "Reference of this spouse's residence certificate",
    documents: "Documents",
    singleStatusCert: "Single-status certificate",
    prevMarried: "Previously married",
    prevMarriedHint: "Requires divorce / widowhood proof",
    priorMaritalProof: "Divorce / widowhood proof",
    foreignSpouseNote:
      "Foreign spouse: documents under Decree 198/PM & Notice 1144 are required; approval involves the MoPS Foreigner Management Department.",
    foreignDocs: "Foreign-spouse documents",
    foreignDocsHint: "Decree 198/PM & Notice 1144 papers",
    additionalDetails: "Additional details (optional)",
    ethnicity: "Ethnicity",
    religion: "Religion",
    ethnicGroup: "Ethnic Group",
    occupation: "Occupation",
    occupationPh: "Occupation",

    // ── DocUpload ──
    uploadDocument: "Upload document",
    pdfOrImage: "PDF or image",

    // ── Step 4 — Documents ──
    docsNote:
      "Shared documents for the couple. Single-status certificates and any foreign-spouse papers are captured per spouse in the previous steps.",
    medicalCert: "Medical certificate (couple)",
    engagementMinute: "Minute of engagement",
    engagementMinuteHint: "Engagement minute supporting the application",

    // ── Step 5 — Registration ──
    dateOfMarriage: "Date of Marriage",
    placeOfRegistration: "Place of Registration",
    placeOfRegistrationPh: "DoHA office",
    witnessesNote: "Three witnesses are required at registration.",
    witness: "Witness {n}",
    witnessName: "Name",
    witnessNamePh: "Witness full name",
    witnessId: "ID No.",
    witnessIdPh: "ID number",
    signNote:
      "The couple and witnesses sign at registration; the registrar applies a protected e-signature in the back office.",

    // ── Step 6 — Review ──
    reviewNote:
      "Please review before submitting. The registrar reviews eligibility, then registers the marriage before 3 witnesses.",
    reviewHeader: "Header",
    reviewProvinceDistrictVillage: "Province / District / Village",
    reviewSpouseA: "Spouse A",
    reviewSpouseB: "Spouse B",
    reviewName: "Name",
    reviewNationality: "Nationality",
    reviewIdPassport: "ID / Passport",
    reviewRegistration: "Registration",
    reviewDateOfMarriage: "Date of marriage",
    reviewPlace: "Place",
    reviewWitnesses: "Witnesses",
    dash: "—",

    // ── Buttons ──
    continue: "Continue",
    submitting: "Submitting…",
    pay: "Pay {amount}",

    // ── Success ──
    successTitle: "Application Submitted!",
    successBody:
      "Your marriage application has been received. The district registrar will review eligibility before registration.",
    successCouple: "Couple",
    successDocumentNo: "Document No.",
    successEstReview: "Est. review",
    successEstReviewValue: "≤ 3 working days",
    successStatus: "Status",
    successStatusValue: "Submitted",
    backToHome: "Back to Home",
    trackHint: "Track your application in the History tab",
  },
  lo: {
    // ── Header / sub-header ──
    title: "ໃບຢັ້ງຢືນການແຕ່ງງານ",
    subtitle: "ການຍື່ນຄຳຮ້ອງອອນລາຍ",
    serviceName: "ໃບຢັ້ງຢືນການແຕ່ງງານ",

    // ── Step labels & subtitles ──
    step1Title: "ຫົວເລື່ອງ",
    step1Subtitle: "ເຂດອຳນາດ ແລະ ລາຍລະອຽດເອກະສານ",
    step2Title: "ຄູ່ສົມລົດ ກ",
    step2Subtitle: "ຂໍ້ມູນຂອງຄູ່ສົມລົດຝ່າຍທີໜຶ່ງ",
    step3Title: "ຄູ່ສົມລົດ ຂ",
    step3Subtitle: "ຂໍ້ມູນຂອງຄູ່ສົມລົດຝ່າຍທີສອງ",
    step4Title: "ເອກະສານ",
    step4Subtitle: "ເອກະສານປະກອບສຳລັບຄູ່ສົມລົດ",
    step5Title: "ການຈົດທະບຽນ",
    step5Subtitle: "ວັນທີ, ສະຖານທີ ແລະ ພະຍານ",
    step6Title: "ກວດສອບ",
    step6Subtitle: "ກວດຄຳຮ້ອງຂອງທ່ານ",
    step7Title: "ການຊຳລະເງິນ",
    step7Subtitle: "ຄ່າທຳນຽມບໍລິການ",
    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // ── Step 1 — Header ──
    documentNo: "ເລກທີເອກະສານ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",
    headerNote:
      "ຄຳຮ້ອງຈະໄດ້ຮັບການຢັ້ງຢືນຈາກນາຍບ້ານ, ຈາກນັ້ນຈຶ່ງຈະຖືກກວດສອບ ແລະ ຈົດທະບຽນທີ່ຫ້ອງການເມືອງຕໍ່ໜ້າພະຍານ 3 ຄົນ.",

    // ── Step 2 / 3 intros ──
    spouseAIntro: "ຂໍ້ມູນຂອງຄູ່ສົມລົດຝ່າຍທີໜຶ່ງ.",
    spouseBIntro: "ຂໍ້ມູນຂອງຄູ່ສົມລົດຝ່າຍທີສອງ.",

    // ── Spouse fields ──
    fullName: "ຊື່ ແລະ ນາມສະກຸນ (ລາວ / ອັງກິດ)",
    fullNamePh: "ຊື່ ແລະ ນາມສະກຸນຂອງຄູ່ສົມລົດ",
    dob: "ວັນເດືອນປີເກີດ",
    gender: "ເພດ",
    selectPh: "ເລືອກ...",
    nationality: "ສັນຊາດ",
    idOrPassport: "ເລກບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ",
    idOrPassportPh: "ບັດປະຈຳຕົວ (ລາວ) ຫຼື ໜັງສືຜ່ານແດນ (ຕ່າງປະເທດ)",
    currentAddress: "ທີ່ຢູ່ປັດຈຸບັນ",
    houseNo: "ເລກທີເຮືອນ",
    houseNoPh: "ເລກທີເຮືອນ",
    village: "ບ້ານ",
    residenceCertRef: "ເລກອ້າງອີງໃບຢັ້ງຢືນທີ່ຢູ່",
    residenceCertRefPh: "ເລກອ້າງອີງໃບຢັ້ງຢືນທີ່ຢູ່ຂອງຄູ່ສົມລົດຝ່າຍນີ້",
    documents: "ເອກະສານ",
    singleStatusCert: "ໃບຢັ້ງຢືນສະຖານະໂສດ",
    prevMarried: "ເຄີຍແຕ່ງງານມາກ່ອນ",
    prevMarriedHint: "ຕ້ອງມີໃບຢັ້ງຢືນການຢ່າຮ້າງ / ການເປັນໝ້າຍ",
    priorMaritalProof: "ໃບຢັ້ງຢືນການຢ່າຮ້າງ / ການເປັນໝ້າຍ",
    foreignSpouseNote:
      "ຄູ່ສົມລົດຕ່າງປະເທດ: ຕ້ອງມີເອກະສານຕາມດຳລັດ 198/ນຍ ແລະ ແຈ້ງການ 1144; ການອະນຸມັດກ່ຽວຂ້ອງກັບກົມຄຸ້ມຄອງຄົນຕ່າງປະເທດ ກະຊວງ ປກສ.",
    foreignDocs: "ເອກະສານຄູ່ສົມລົດຕ່າງປະເທດ",
    foreignDocsHint: "ເອກະສານຕາມດຳລັດ 198/ນຍ ແລະ ແຈ້ງການ 1144",
    additionalDetails: "ຂໍ້ມູນເພີ່ມເຕີມ (ບໍ່ບັງຄັບ)",
    ethnicity: "ຊົນເຜົ່າ",
    religion: "ສາສະໜາ",
    ethnicGroup: "ໝວດຊົນເຜົ່າ",
    occupation: "ອາຊີບ",
    occupationPh: "ອາຊີບ",

    // ── DocUpload ──
    uploadDocument: "ອັບໂຫຼດເອກະສານ",
    pdfOrImage: "PDF ຫຼື ຮູບພາບ",

    // ── Step 4 — Documents ──
    docsNote:
      "ເອກະສານຮ່ວມສຳລັບຄູ່ສົມລົດ. ໃບຢັ້ງຢືນສະຖານະໂສດ ແລະ ບັນດາເອກະສານຂອງຄູ່ສົມລົດຕ່າງປະເທດແຕ່ລະຝ່າຍທີ່ໄດ້ບັນທຶກໃນຂັ້ນຕອນກ່ອນໜ້າ.",
    medicalCert: "ໃບຢັ້ງຢືນສຸຂະພາບ (ຄູ່ສົມລົດ)",
    engagementMinute: "ບົດບັນທຶກການໝັ້ນໝາຍ",
    engagementMinuteHint: "ບົດບັນທຶກການໝັ້ນໝາຍປະກອບຄຳຮ້ອງ",

    // ── Step 5 — Registration ──
    dateOfMarriage: "ວັນທີແຕ່ງງານ",
    placeOfRegistration: "ສະຖານທີຈົດທະບຽນ",
    placeOfRegistrationPh: "ຫ້ອງການ ພນທ",
    witnessesNote: "ຕ້ອງມີພະຍານ 3 ຄົນ ໃນເວລາຈົດທະບຽນ.",
    witness: "ພະຍານ {n}",
    witnessName: "ຊື່",
    witnessNamePh: "ຊື່ ແລະ ນາມສະກຸນຂອງພະຍານ",
    witnessId: "ເລກບັດປະຈຳຕົວ",
    witnessIdPh: "ເລກບັດປະຈຳຕົວ",
    signNote:
      "ຄູ່ສົມລົດ ແລະ ພະຍານຈະໄດ້ເຊັນໃນເວລາຈົດທະບຽນ; ນາຍທະບຽນຈະໃສ່ລາຍເຊັນອີເລັກໂທຣນິກທີ່ມີການປ້ອງກັນໄວ້ໃນຫ້ອງການ.",

    // ── Step 6 — Review ──
    reviewNote:
      "ກະລຸນາກວດສອບຄືນກ່ອນຍື່ນ. ນາຍທະບຽນຈະກວດສອບເງື່ອນໄຂ, ຈາກນັ້ນຈຶ່ງມີການຈົດທະບຽນການແຕ່ງງານຕໍ່ໜ້າພະຍານທັ້ງ 3 ຄົນ.",
    reviewHeader: "ຫົວເລື່ອງ",
    reviewProvinceDistrictVillage: "ແຂວງ / ເມືອງ / ບ້ານ",
    reviewSpouseA: "ຄູ່ສົມລົດ ກ",
    reviewSpouseB: "ຄູ່ສົມລົດ ຂ",
    reviewName: "ຊື່",
    reviewNationality: "ສັນຊາດ",
    reviewIdPassport: "ບັດປະຈຳຕົວ / ໜັງສືຜ່ານແດນ",
    reviewRegistration: "ການຈົດທະບຽນ",
    reviewDateOfMarriage: "ວັນທີແຕ່ງງານ",
    reviewPlace: "ສະຖານທີ",
    reviewWitnesses: "ພະຍານ",
    dash: "—",

    // ── Buttons ──
    continue: "ສືບຕໍ່",
    submitting: "ກຳລັງຍື່ນ…",
    pay: "ຊຳລະ {amount}",

    // ── Success ──
    successTitle: "ຍື່ນຄຳຮ້ອງສຳເລັດ!",
    successBody:
      "ໄດ້ຮັບຄຳຮ້ອງການແຕ່ງງານຂອງທ່ານແລ້ວ. ນາຍທະບຽນເມືອງຈະກວດສອບເງື່ອນໄຂກ່ອນການຈົດທະບຽນ.",
    successCouple: "ຄູ່ສົມລົດ",
    successDocumentNo: "ເລກທີເອກະສານ",
    successEstReview: "ໄລຍະກວດສອບໂດຍປະມານ",
    successEstReviewValue: "ບໍ່ເກີນ 3 ວັນລັດຖະການ",
    successStatus: "ສະຖານະ",
    successStatusValue: "ຍື່ນແລ້ວ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຄຳຮ້ອງຂອງທ່ານໃນແຖບປະຫວັດ",
  },
});
