import { ns } from "../types";

export const resident = ns({
  en: {
    // Header
    headerTitle: "Residence Certificate",
    headerSubtitle: "Online Application",

    // Steps
    step1Title: "Verify Identity",
    step1Subtitle: "Upload your ID — we'll read your details automatically",
    step2Title: "Applicant",
    step2Subtitle: "Confirm the details read from your ID",
    step3Title: "Location & Authority",
    step3Subtitle: "Jurisdiction and certifying village office",
    step4Title: "Current Residence",
    step4Subtitle: "The address being attested",
    step5Title: "Household & Purpose",
    step5Subtitle: "Family book reference, parentage and purpose",
    step6Title: "Payment",
    step6Subtitle: "Service fee",
    stepOf: "Step {n} of {m}",

    // Nationalities
    natLao: "Lao",
    natThai: "Thai",
    natVietnamese: "Vietnamese",
    natChinese: "Chinese",
    natCambodian: "Cambodian",
    natMyanmar: "Myanmar",
    natAmerican: "American",
    natFrench: "French",
    natOther: "Other",

    // Purposes
    purposeEmployment: "Employment / Job Application",
    purposeBank: "Bank Account Opening",
    purposeSchool: "School / University Enrollment",
    purposeTravel: "Travel / Visa Application",
    purposeProperty: "Property Transaction",
    purposePermit: "Government Permit",
    purposeOther: "Other",

    // Upload box
    uploadTap: "Tap to upload photo",

    // Step 1 — Verify Identity
    step1Notice:
      "Upload clear photos of both sides of your National ID (or passport). We'll read your name and details automatically. Renters and foreigners should also bring a lease contract to the village office.",
    frontIdLabel: "ID Card — Front Side",
    backIdLabel: "ID Card — Back Side",
    idSublabel: "Photo or scan • JPG, PNG",
    readingId: "Reading your ID…",
    detailsDetected: "Details detected",
    detectedSummary: "{name} · Age {age} · {nationality}. Confirm them on the next step.",

    // Step 2 — Applicant
    refNoLabel: "Ref. No.",
    autoGenerated: "Auto-generated",
    autoFilledNotice: "Auto-filled from your ID — please review and correct if anything is wrong.",
    citizenNameLabel: "Citizen's Name",
    citizenNamePlaceholder: "Full name of the applicant",
    ageLabel: "Age",
    agePlaceholder: "e.g. 34",
    nationalityLabel: "Nationality",
    selectPlaceholder: "Select...",
    occupationLabel: "Occupation (optional)",
    occupationPlaceholder: "Current occupation or profession",
    pictureLabel: "Picture (3×4) — if applicable",
    pictureSublabel: "3×4 cm photo • JPG, PNG",

    // Step 3 — Location & Authority
    villageNameLabel: "Village's Name",
    villageChiefLabel: "Village Chief's Name (Nai Ban)",
    villageChiefPlaceholder: "Full name of the certifying Village Chief",
    certifyingJurisdictionLabel: "Certifying District / Province",
    certifyingJurisdictionPlaceholder: "Jurisdiction of the certifying authority",

    // Step 4 — Current Residence
    step4Notice: "This is the address being attested — the village where you currently reside.",
    currentVillageLabel: "Current Village",
    currentVillagePlaceholder: "e.g. Ban Phonxay",
    houseNoLabel: "House No.",
    houseNoPlaceholder: "House number",
    unitLabel: "Unit / Nuay Ban (if applicable)",
    unitPlaceholder: "Administrative unit",
    groupLabel: "Group / Khum (if applicable)",
    groupPlaceholder: "Cluster group",

    // Step 5 — Household, Parentage & Purpose
    householdHeading: "Household reference (family book)",
    censusBookNoLabel: "Household Census Book No.",
    censusBookNoPlaceholder: "Family book number",
    censusBookDateLabel: "Census Book Issue Date (if applicable)",
    censusDistrictProvinceLabel: "Census District / Province (if applicable)",
    censusDistrictProvincePlaceholder: "Registration jurisdiction",
    parentageHeading: "Parentage (if applicable)",
    fatherLabel: "Child of Mr. (father)",
    fatherPlaceholder: "Father's full name",
    motherLabel: "and Mrs. (mother)",
    motherPlaceholder: "Mother's full name",
    nativePlaceLabel: "Native Village / District / Province (optional)",
    nativePlacePlaceholder: "Home place of the family record",
    purposeHeading: "Purpose",
    purposeLabel: "This certificate is used for",
    purposePlaceholder: "Select purpose...",

    // Step 6 — Payment
    paymentServiceName: "Residence Certificate",

    // Bottom CTA
    processingPayment: "Processing payment…",
    pay: "Pay {amount}",
    continue: "Continue",

    // Success
    successTitle: "Application Submitted!",
    successMessage: "Your Residence Certificate application has been received and is now being processed.",
    successApplicant: "Applicant",
    successReference: "Reference No.",
    successCompletion: "Est. completion",
    successCompletionValue: "Same day (target)",
    successStatus: "Status",
    successStatusValue: "Processing",
    backToHome: "Back to Home",
    trackHint: "Track your application in the History tab",
  },
  lo: {
    // Header
    headerTitle: "ໃບຢັ້ງຢືນທີ່ຢູ່ອາໄສ",
    headerSubtitle: "ການຍື່ນຄຳຮ້ອງທາງອອນລາຍ",

    // Steps
    step1Title: "ຢືນຢັນຕົວຕົນ",
    step1Subtitle: "ອັບໂຫຼດບັດປະຈຳຕົວ — ລະບົບຈະອ່ານຂໍ້ມູນຂອງທ່ານໂດຍອັດຕະໂນມັດ",
    step2Title: "ຜູ້ຍື່ນຄຳຮ້ອງ",
    step2Subtitle: "ກວດຢືນຢັນຂໍ້ມູນທີ່ອ່ານໄດ້ຈາກບັດປະຈຳຕົວຂອງທ່ານ",
    step3Title: "ສະຖານທີ່ & ອຳນາດການປົກຄອງ",
    step3Subtitle: "ເຂດອຳນາດການປົກຄອງ ແລະ ຫ້ອງການບ້ານທີ່ອອກໃບຢັ້ງຢືນ",
    step4Title: "ທີ່ຢູ່ອາໄສປັດຈຸບັນ",
    step4Subtitle: "ທີ່ຢູ່ທີ່ກຳລັງຮັບຮອງ",
    step5Title: "ສຳມະໂນຄົວ & ຈຸດປະສົງ",
    step5Subtitle: "ຂໍ້ມູນປຶ້ມສຳມະໂນຄົວ, ບິດາມານດາ ແລະ ຈຸດປະສົງ",
    step6Title: "ການຊຳລະເງິນ",
    step6Subtitle: "ຄ່າທຳນຽມບໍລິການ",
    stepOf: "ຂັ້ນຕອນ {n} ຈາກ {m}",

    // Nationalities
    natLao: "ລາວ",
    natThai: "ໄທ",
    natVietnamese: "ຫວຽດນາມ",
    natChinese: "ຈີນ",
    natCambodian: "ກຳປູເຈຍ",
    natMyanmar: "ມຽນມາ",
    natAmerican: "ອາເມລິກາ",
    natFrench: "ຝຣັ່ງ",
    natOther: "ອື່ນໆ",

    // Purposes
    purposeEmployment: "ການເຮັດວຽກ / ສະໝັກວຽກ",
    purposeBank: "ການເປີດບັນຊີທະນາຄານ",
    purposeSchool: "ການລົງທະບຽນໂຮງຮຽນ / ມະຫາວິທະຍາໄລ",
    purposeTravel: "ການເດີນທາງ / ຂໍວີຊາ",
    purposeProperty: "ການເຮັດທຸລະກຳຊັບສິນ",
    purposePermit: "ໃບອະນຸຍາດຈາກລັດຖະການ",
    purposeOther: "ອື່ນໆ",

    // Upload box
    uploadTap: "ແຕະເພື່ອອັບໂຫຼດຮູບ",

    // Step 1 — Verify Identity
    step1Notice:
      "ອັບໂຫຼດຮູບທີ່ຊັດເຈນຂອງບັດປະຈຳຕົວແຫ່ງຊາດ (ຫຼື ໜັງສືຜ່ານແດນ) ທັງສອງດ້ານ. ລະບົບຈະອ່ານຊື່ ແລະ ຂໍ້ມູນຂອງທ່ານໂດຍອັດຕະໂນມັດ. ຜູ້ເຊົ່າ ແລະ ຄົນຕ່າງປະເທດຄວນນຳສັນຍາເຊົ່າໄປຫ້ອງການບ້ານນຳ.",
    frontIdLabel: "ບັດປະຈຳຕົວ — ດ້ານໜ້າ",
    backIdLabel: "ບັດປະຈຳຕົວ — ດ້ານຫຼັງ",
    idSublabel: "ຮູບຖ່າຍ ຫຼື ສະແກນ • JPG, PNG",
    readingId: "ກຳລັງອ່ານບັດປະຈຳຕົວຂອງທ່ານ…",
    detailsDetected: "ກວດພົບຂໍ້ມູນແລ້ວ",
    detectedSummary: "{name} · ອາຍຸ {age} · {nationality}. ກະລຸນາຢືນຢັນໃນຂັ້ນຕອນຕໍ່ໄປ.",

    // Step 2 — Applicant
    refNoLabel: "ເລກອ້າງອີງ",
    autoGenerated: "ສ້າງອັດຕະໂນມັດ",
    autoFilledNotice: "ຕື່ມຂໍ້ມູນອັດຕະໂນມັດຈາກບັດປະຈຳຕົວຂອງທ່ານ — ກະລຸນາກວດຄືນ ແລະ ແກ້ໄຂຫາກມີຂໍ້ຜິດພາດ.",
    citizenNameLabel: "ຊື່ ແລະ ນາມສະກຸນ",
    citizenNamePlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງຜູ້ຍື່ນຄຳຮ້ອງ",
    ageLabel: "ອາຍຸ",
    agePlaceholder: "ຕົວຢ່າງ 34",
    nationalityLabel: "ສັນຊາດ",
    selectPlaceholder: "ເລືອກ...",
    occupationLabel: "ອາຊີບ (ບໍ່ບັງຄັບ)",
    occupationPlaceholder: "ອາຊີບ ຫຼື ວິຊາຊີບປັດຈຸບັນ",
    pictureLabel: "ຮູບຖ່າຍ (3×4) — ຖ້າມີ",
    pictureSublabel: "ຮູບຖ່າຍ 3×4 ຊມ • JPG, PNG",

    // Step 3 — Location & Authority
    villageNameLabel: "ຊື່ບ້ານ",
    villageChiefLabel: "ຊື່ນາຍບ້ານ",
    villageChiefPlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງນາຍບ້ານຜູ້ຮັບຮອງ",
    certifyingJurisdictionLabel: "ເມືອງ / ແຂວງ ທີ່ຮັບຮອງ",
    certifyingJurisdictionPlaceholder: "ເຂດອຳນາດການປົກຄອງຂອງຜູ້ຮັບຮອງ",

    // Step 4 — Current Residence
    step4Notice: "ນີ້ແມ່ນທີ່ຢູ່ທີ່ກຳລັງຮັບຮອງ — ບ້ານທີ່ທ່ານອາໄສຢູ່ໃນປັດຈຸບັນ.",
    currentVillageLabel: "ບ້ານຢູ່ປັດຈຸບັນ",
    currentVillagePlaceholder: "ຕົວຢ່າງ ບ້ານໂພນໄຊ",
    houseNoLabel: "ເລກທີ່ເຮືອນ",
    houseNoPlaceholder: "ເລກທີ່ເຮືອນ",
    unitLabel: "ໜ່ວຍ / ໜ່ວຍບ້ານ (ຖ້າມີ)",
    unitPlaceholder: "ໜ່ວຍບໍລິຫານ",
    groupLabel: "ກຸ່ມ / ຄຸ້ມ (ຖ້າມີ)",
    groupPlaceholder: "ກຸ່ມຄຸ້ມ",

    // Step 5 — Household, Parentage & Purpose
    householdHeading: "ຂໍ້ມູນອ້າງອີງສຳມະໂນຄົວ (ປຶ້ມສຳມະໂນຄົວ)",
    censusBookNoLabel: "ເລກປຶ້ມສຳມະໂນຄົວ",
    censusBookNoPlaceholder: "ເລກປຶ້ມສຳມະໂນຄົວ",
    censusBookDateLabel: "ວັນທີ່ອອກປຶ້ມສຳມະໂນຄົວ (ຖ້າມີ)",
    censusDistrictProvinceLabel: "ເມືອງ / ແຂວງ ທີ່ຂຶ້ນທະບຽນ (ຖ້າມີ)",
    censusDistrictProvincePlaceholder: "ເຂດອຳນາດການຂຶ້ນທະບຽນ",
    parentageHeading: "ບິດາມານດາ (ຖ້າມີ)",
    fatherLabel: "ເປັນບຸດຂອງທ້າວ (ບິດາ)",
    fatherPlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງບິດາ",
    motherLabel: "ແລະ ນາງ (ມານດາ)",
    motherPlaceholder: "ຊື່ ແລະ ນາມສະກຸນຂອງມານດາ",
    nativePlaceLabel: "ບ້ານ / ເມືອງ / ແຂວງ ເກີດ (ບໍ່ບັງຄັບ)",
    nativePlacePlaceholder: "ບ້ານເກີດຕາມທະບຽນຄອບຄົວ",
    purposeHeading: "ຈຸດປະສົງ",
    purposeLabel: "ໃບຢັ້ງຢືນນີ້ໃຊ້ສຳລັບ",
    purposePlaceholder: "ເລືອກຈຸດປະສົງ...",

    // Step 6 — Payment
    paymentServiceName: "ໃບຢັ້ງຢືນທີ່ຢູ່ອາໄສ",

    // Bottom CTA
    processingPayment: "ກຳລັງດຳເນີນການຊຳລະເງິນ…",
    pay: "ຊຳລະ {amount}",
    continue: "ສືບຕໍ່",

    // Success
    successTitle: "ຍື່ນຄຳຮ້ອງສຳເລັດແລ້ວ!",
    successMessage: "ຄຳຮ້ອງຂໍໃບຢັ້ງຢືນທີ່ຢູ່ອາໄສຂອງທ່ານໄດ້ຖຶກບັນທຶກແລ້ວ ແລະ ກຳລັງຢູ່ໃນຂະບວນການດຳເນີນການ.",
    successApplicant: "ຜູ້ຍື່ນຄຳຮ້ອງ",
    successReference: "ເລກອ້າງອີງ",
    successCompletion: "ຄາດວ່າຈະສຳເລັດ",
    successCompletionValue: "ໄດ້ຮັບພາຍໃນມື້ດຽວກັນ (ຄາດໝາຍ)",
    successStatus: "ສະຖານະ",
    successStatusValue: "ກຳລັງດຳເນີນການ",
    backToHome: "ກັບໄປໜ້າຫຼັກ",
    trackHint: "ຕິດຕາມຄຳຮ້ອງຂອງທ່ານໄດ້ໃນແຖບປະຫວັດ",
  },
});
